package org.apache.poi.hssf.record;

import org.apache.poi.util.BitField;
import org.apache.poi.util.HexDump;
import org.apache.poi.util.LittleEndian;

/* JADX INFO: loaded from: classes3.dex */
public class TextRecord extends Record {
    public static final short DATA_LABEL_PLACEMENT_ABOVE = 5;
    public static final short DATA_LABEL_PLACEMENT_AUTO = 9;
    public static final short DATA_LABEL_PLACEMENT_AXIS = 4;
    public static final short DATA_LABEL_PLACEMENT_BELOW = 6;
    public static final short DATA_LABEL_PLACEMENT_CENTER = 3;
    public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = 0;
    public static final short DATA_LABEL_PLACEMENT_INSIDE = 2;
    public static final short DATA_LABEL_PLACEMENT_LEFT = 7;
    public static final short DATA_LABEL_PLACEMENT_OUTSIDE = 1;
    public static final short DATA_LABEL_PLACEMENT_RIGHT = 8;
    public static final short DATA_LABEL_PLACEMENT_USER_MOVED = 10;
    public static final short DISPLAY_MODE_OPAQUE = 2;
    public static final short DISPLAY_MODE_TRANSPARENT = 1;
    public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = 3;
    public static final byte HORIZONTAL_ALIGNMENT_CENTER = 2;
    public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte HORIZONTAL_ALIGNMENT_LEFT = 1;
    public static final short ROTATION_NONE = 0;
    public static final short ROTATION_ROTATED_90_DEGREES = 2;
    public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = 3;
    public static final short ROTATION_TOP_TO_BOTTOM = 1;
    public static final byte VERTICAL_ALIGNMENT_BOTTOM = 3;
    public static final byte VERTICAL_ALIGNMENT_CENTER = 2;
    public static final byte VERTICAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte VERTICAL_ALIGNMENT_TOP = 1;
    public static final short sid = 4133;
    private BitField autoBackground;
    private BitField autoColor;
    private BitField autoGeneratedText;
    private BitField autoLabelDeleted;
    private BitField dataLabelPlacement;
    private short field_10_indexOfColorValue;
    private short field_11_options2;
    private short field_12_textRotation;
    private byte field_1_horizontalAlignment;
    private byte field_2_verticalAlignment;
    private short field_3_displayMode;
    private int field_4_rgbColor;
    private int field_5_x;
    private int field_6_y;
    private int field_7_width;
    private int field_8_height;
    private short field_9_options1;
    private BitField generated;
    private BitField rotation;
    private BitField showBubbleSizes;
    private BitField showCategoryLabelAsPercentage;
    private BitField showKey;
    private BitField showLabel;
    private BitField showValue;
    private BitField showValueAsPercentage;
    private BitField vertical;

    @Override // org.apache.poi.hssf.record.Record
    public int getRecordSize() {
        return 36;
    }

    @Override // org.apache.poi.hssf.record.Record
    public short getSid() {
        return sid;
    }

    public TextRecord() {
        this.autoColor = new BitField(1);
        this.showKey = new BitField(2);
        this.showValue = new BitField(4);
        this.vertical = new BitField(8);
        this.autoGeneratedText = new BitField(16);
        this.generated = new BitField(32);
        this.autoLabelDeleted = new BitField(64);
        this.autoBackground = new BitField(128);
        this.rotation = new BitField(1792);
        this.showCategoryLabelAsPercentage = new BitField(2048);
        this.showValueAsPercentage = new BitField(4096);
        this.showBubbleSizes = new BitField(8192);
        this.showLabel = new BitField(16384);
        this.dataLabelPlacement = new BitField(15);
    }

    public TextRecord(short s, short s2, byte[] bArr) {
        super(s, s2, bArr);
        this.autoColor = new BitField(1);
        this.showKey = new BitField(2);
        this.showValue = new BitField(4);
        this.vertical = new BitField(8);
        this.autoGeneratedText = new BitField(16);
        this.generated = new BitField(32);
        this.autoLabelDeleted = new BitField(64);
        this.autoBackground = new BitField(128);
        this.rotation = new BitField(1792);
        this.showCategoryLabelAsPercentage = new BitField(2048);
        this.showValueAsPercentage = new BitField(4096);
        this.showBubbleSizes = new BitField(8192);
        this.showLabel = new BitField(16384);
        this.dataLabelPlacement = new BitField(15);
    }

    public TextRecord(short s, short s2, byte[] bArr, int i) {
        super(s, s2, bArr, i);
        this.autoColor = new BitField(1);
        this.showKey = new BitField(2);
        this.showValue = new BitField(4);
        this.vertical = new BitField(8);
        this.autoGeneratedText = new BitField(16);
        this.generated = new BitField(32);
        this.autoLabelDeleted = new BitField(64);
        this.autoBackground = new BitField(128);
        this.rotation = new BitField(1792);
        this.showCategoryLabelAsPercentage = new BitField(2048);
        this.showValueAsPercentage = new BitField(4096);
        this.showBubbleSizes = new BitField(8192);
        this.showLabel = new BitField(16384);
        this.dataLabelPlacement = new BitField(15);
    }

    @Override // org.apache.poi.hssf.record.Record
    protected void validateSid(short s) {
        if (s != 4133) {
            throw new RecordFormatException("Not a Text record");
        }
    }

    @Override // org.apache.poi.hssf.record.Record
    protected void fillFields(byte[] bArr, short s, int i) {
        this.field_1_horizontalAlignment = bArr[0 + i];
        this.field_2_verticalAlignment = bArr[1 + i];
        this.field_3_displayMode = LittleEndian.getShort(bArr, 2 + i);
        this.field_4_rgbColor = LittleEndian.getInt(bArr, 4 + i);
        this.field_5_x = LittleEndian.getInt(bArr, 8 + i);
        this.field_6_y = LittleEndian.getInt(bArr, 12 + i);
        this.field_7_width = LittleEndian.getInt(bArr, 16 + i);
        this.field_8_height = LittleEndian.getInt(bArr, 20 + i);
        this.field_9_options1 = LittleEndian.getShort(bArr, 24 + i);
        this.field_10_indexOfColorValue = LittleEndian.getShort(bArr, 26 + i);
        this.field_11_options2 = LittleEndian.getShort(bArr, 28 + i);
        this.field_12_textRotation = LittleEndian.getShort(bArr, 30 + i);
    }

    @Override // org.apache.poi.hssf.record.Record
    public String toString() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("[TEXT]\n");
        stringBuffer.append("    .horizontalAlignment  = ").append("0x").append(HexDump.toHex(getHorizontalAlignment())).append(" (").append((int) getHorizontalAlignment()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .verticalAlignment    = ").append("0x").append(HexDump.toHex(getVerticalAlignment())).append(" (").append((int) getVerticalAlignment()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .displayMode          = ").append("0x").append(HexDump.toHex(getDisplayMode())).append(" (").append((int) getDisplayMode()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .rgbColor             = ").append("0x").append(HexDump.toHex(getRgbColor())).append(" (").append(getRgbColor()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .x                    = ").append("0x").append(HexDump.toHex(getX())).append(" (").append(getX()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .y                    = ").append("0x").append(HexDump.toHex(getY())).append(" (").append(getY()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .width                = ").append("0x").append(HexDump.toHex(getWidth())).append(" (").append(getWidth()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .height               = ").append("0x").append(HexDump.toHex(getHeight())).append(" (").append(getHeight()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .options1             = ").append("0x").append(HexDump.toHex(getOptions1())).append(" (").append((int) getOptions1()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("         .autoColor                = ").append(isAutoColor()).append('\n');
        stringBuffer.append("         .showKey                  = ").append(isShowKey()).append('\n');
        stringBuffer.append("         .showValue                = ").append(isShowValue()).append('\n');
        stringBuffer.append("         .vertical                 = ").append(isVertical()).append('\n');
        stringBuffer.append("         .autoGeneratedText        = ").append(isAutoGeneratedText()).append('\n');
        stringBuffer.append("         .generated                = ").append(isGenerated()).append('\n');
        stringBuffer.append("         .autoLabelDeleted         = ").append(isAutoLabelDeleted()).append('\n');
        stringBuffer.append("         .autoBackground           = ").append(isAutoBackground()).append('\n');
        stringBuffer.append("         .rotation                 = ").append((int) getRotation()).append('\n');
        stringBuffer.append("         .showCategoryLabelAsPercentage     = ").append(isShowCategoryLabelAsPercentage()).append('\n');
        stringBuffer.append("         .showValueAsPercentage     = ").append(isShowValueAsPercentage()).append('\n');
        stringBuffer.append("         .showBubbleSizes          = ").append(isShowBubbleSizes()).append('\n');
        stringBuffer.append("         .showLabel                = ").append(isShowLabel()).append('\n');
        stringBuffer.append("    .indexOfColorValue    = ").append("0x").append(HexDump.toHex(getIndexOfColorValue())).append(" (").append((int) getIndexOfColorValue()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .options2             = ").append("0x").append(HexDump.toHex(getOptions2())).append(" (").append((int) getOptions2()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("         .dataLabelPlacement       = ").append((int) getDataLabelPlacement()).append('\n');
        stringBuffer.append("    .textRotation         = ").append("0x").append(HexDump.toHex(getTextRotation())).append(" (").append((int) getTextRotation()).append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("[/TEXT]\n");
        return stringBuffer.toString();
    }

    @Override // org.apache.poi.hssf.record.Record
    public int serialize(int i, byte[] bArr) {
        LittleEndian.putShort(bArr, i + 0, sid);
        LittleEndian.putShort(bArr, i + 2, (short) (getRecordSize() - 4));
        bArr[i + 4 + 0] = this.field_1_horizontalAlignment;
        bArr[i + 5 + 0] = this.field_2_verticalAlignment;
        LittleEndian.putShort(bArr, i + 6 + 0, this.field_3_displayMode);
        LittleEndian.putInt(bArr, i + 8 + 0, this.field_4_rgbColor);
        LittleEndian.putInt(bArr, i + 12 + 0, this.field_5_x);
        LittleEndian.putInt(bArr, i + 16 + 0, this.field_6_y);
        LittleEndian.putInt(bArr, i + 20 + 0, this.field_7_width);
        LittleEndian.putInt(bArr, i + 24 + 0, this.field_8_height);
        LittleEndian.putShort(bArr, i + 28 + 0, this.field_9_options1);
        LittleEndian.putShort(bArr, i + 30 + 0, this.field_10_indexOfColorValue);
        LittleEndian.putShort(bArr, i + 32 + 0, this.field_11_options2);
        LittleEndian.putShort(bArr, i + 34 + 0, this.field_12_textRotation);
        return getRecordSize();
    }

    @Override // org.apache.poi.hssf.record.Record
    public Object clone() {
        TextRecord textRecord = new TextRecord();
        textRecord.field_1_horizontalAlignment = this.field_1_horizontalAlignment;
        textRecord.field_2_verticalAlignment = this.field_2_verticalAlignment;
        textRecord.field_3_displayMode = this.field_3_displayMode;
        textRecord.field_4_rgbColor = this.field_4_rgbColor;
        textRecord.field_5_x = this.field_5_x;
        textRecord.field_6_y = this.field_6_y;
        textRecord.field_7_width = this.field_7_width;
        textRecord.field_8_height = this.field_8_height;
        textRecord.field_9_options1 = this.field_9_options1;
        textRecord.field_10_indexOfColorValue = this.field_10_indexOfColorValue;
        textRecord.field_11_options2 = this.field_11_options2;
        textRecord.field_12_textRotation = this.field_12_textRotation;
        return textRecord;
    }

    public byte getHorizontalAlignment() {
        return this.field_1_horizontalAlignment;
    }

    public void setHorizontalAlignment(byte b) {
        this.field_1_horizontalAlignment = b;
    }

    public byte getVerticalAlignment() {
        return this.field_2_verticalAlignment;
    }

    public void setVerticalAlignment(byte b) {
        this.field_2_verticalAlignment = b;
    }

    public short getDisplayMode() {
        return this.field_3_displayMode;
    }

    public void setDisplayMode(short s) {
        this.field_3_displayMode = s;
    }

    public int getRgbColor() {
        return this.field_4_rgbColor;
    }

    public void setRgbColor(int i) {
        this.field_4_rgbColor = i;
    }

    public int getX() {
        return this.field_5_x;
    }

    public void setX(int i) {
        this.field_5_x = i;
    }

    public int getY() {
        return this.field_6_y;
    }

    public void setY(int i) {
        this.field_6_y = i;
    }

    public int getWidth() {
        return this.field_7_width;
    }

    public void setWidth(int i) {
        this.field_7_width = i;
    }

    public int getHeight() {
        return this.field_8_height;
    }

    public void setHeight(int i) {
        this.field_8_height = i;
    }

    public short getOptions1() {
        return this.field_9_options1;
    }

    public void setOptions1(short s) {
        this.field_9_options1 = s;
    }

    public short getIndexOfColorValue() {
        return this.field_10_indexOfColorValue;
    }

    public void setIndexOfColorValue(short s) {
        this.field_10_indexOfColorValue = s;
    }

    public short getOptions2() {
        return this.field_11_options2;
    }

    public void setOptions2(short s) {
        this.field_11_options2 = s;
    }

    public short getTextRotation() {
        return this.field_12_textRotation;
    }

    public void setTextRotation(short s) {
        this.field_12_textRotation = s;
    }

    public void setAutoColor(boolean z) {
        this.field_9_options1 = this.autoColor.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoColor() {
        return this.autoColor.isSet(this.field_9_options1);
    }

    public void setShowKey(boolean z) {
        this.field_9_options1 = this.showKey.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowKey() {
        return this.showKey.isSet(this.field_9_options1);
    }

    public void setShowValue(boolean z) {
        this.field_9_options1 = this.showValue.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowValue() {
        return this.showValue.isSet(this.field_9_options1);
    }

    public void setVertical(boolean z) {
        this.field_9_options1 = this.vertical.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isVertical() {
        return this.vertical.isSet(this.field_9_options1);
    }

    public void setAutoGeneratedText(boolean z) {
        this.field_9_options1 = this.autoGeneratedText.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoGeneratedText() {
        return this.autoGeneratedText.isSet(this.field_9_options1);
    }

    public void setGenerated(boolean z) {
        this.field_9_options1 = this.generated.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isGenerated() {
        return this.generated.isSet(this.field_9_options1);
    }

    public void setAutoLabelDeleted(boolean z) {
        this.field_9_options1 = this.autoLabelDeleted.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoLabelDeleted() {
        return this.autoLabelDeleted.isSet(this.field_9_options1);
    }

    public void setAutoBackground(boolean z) {
        this.field_9_options1 = this.autoBackground.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoBackground() {
        return this.autoBackground.isSet(this.field_9_options1);
    }

    public void setRotation(short s) {
        this.field_9_options1 = this.rotation.setShortValue(this.field_9_options1, s);
    }

    public short getRotation() {
        return this.rotation.getShortValue(this.field_9_options1);
    }

    public void setShowCategoryLabelAsPercentage(boolean z) {
        this.field_9_options1 = this.showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowCategoryLabelAsPercentage() {
        return this.showCategoryLabelAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowValueAsPercentage(boolean z) {
        this.field_9_options1 = this.showValueAsPercentage.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowValueAsPercentage() {
        return this.showValueAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowBubbleSizes(boolean z) {
        this.field_9_options1 = this.showBubbleSizes.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowBubbleSizes() {
        return this.showBubbleSizes.isSet(this.field_9_options1);
    }

    public void setShowLabel(boolean z) {
        this.field_9_options1 = this.showLabel.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowLabel() {
        return this.showLabel.isSet(this.field_9_options1);
    }

    public void setDataLabelPlacement(short s) {
        this.field_11_options2 = this.dataLabelPlacement.setShortValue(this.field_11_options2, s);
    }

    public short getDataLabelPlacement() {
        return this.dataLabelPlacement.getShortValue(this.field_11_options2);
    }
}
