package org.apache.poi.ddf;

import android.bluetooth.BluetoothClass;
import android.media.AudioSystem;
import android.media.MediaPlayer;
import android.media.videoeditor.MediaArtistNativeHelper;
import android.media.videoeditor.MediaProperties;
import android.net.UrlQuerySanitizer;
import android.os.FileUtils;
import android.provider.Downloads;
import com.autonavi.amap.mapcore.AMapEngineUtils;
import java.util.HashMap;
import java.util.Map;
import org.apache.commons.net.ftp.FTPReply;
import org.apache.commons.net.nntp.NNTPReply;
import org.apache.commons.net.telnet.TelnetCommand;

/* JADX INFO: loaded from: classes3.dex */
public class EscherProperties {
    public static final short BLIP__BLIPFILENAME = 261;
    public static final short BLIP__BLIPFLAGS = 262;
    public static final short BLIP__BLIPTODISPLAY = 260;
    public static final short BLIP__BRIGHTNESSSETTING = 265;
    public static final short BLIP__CONTRASTSETTING = 264;
    public static final short BLIP__CROPFROMBOTTOM = 257;
    public static final short BLIP__CROPFROMLEFT = 258;
    public static final short BLIP__CROPFROMRIGHT = 259;
    public static final short BLIP__CROPFROMTOP = 256;
    public static final short BLIP__DOUBLEMOD = 268;
    public static final short BLIP__GAMMA = 266;
    public static final short BLIP__NOHITTESTPICTURE = 316;
    public static final short BLIP__PICTUREACTIVE = 319;
    public static final short BLIP__PICTUREBILEVEL = 318;
    public static final short BLIP__PICTUREFILLMOD = 269;
    public static final short BLIP__PICTUREGRAY = 317;
    public static final short BLIP__PICTUREID = 267;
    public static final short BLIP__PICTURELINE = 270;
    public static final short BLIP__PRINTBLIP = 271;
    public static final short BLIP__PRINTBLIPFILENAME = 272;
    public static final short BLIP__PRINTFLAGS = 273;
    public static final short BLIP__TRANSPARENTCOLOR = 263;
    public static final short CALLOUT__CALLOUTACCENTBAR = 890;
    public static final short CALLOUT__CALLOUTANGLE = 834;
    public static final short CALLOUT__CALLOUTDROPSPECIFIED = 836;
    public static final short CALLOUT__CALLOUTDROPTYPE = 835;
    public static final short CALLOUT__CALLOUTLENGTHSPECIFIED = 837;
    public static final short CALLOUT__CALLOUTMINUSX = 892;
    public static final short CALLOUT__CALLOUTMINUSY = 893;
    public static final short CALLOUT__CALLOUTTEXTBORDER = 891;
    public static final short CALLOUT__CALLOUTTYPE = 832;
    public static final short CALLOUT__DROPAUTO = 894;
    public static final short CALLOUT__ISCALLOUT = 889;
    public static final short CALLOUT__LENGTHSPECIFIED = 895;
    public static final short CALLOUT__XYCALLOUTGAP = 833;
    public static final short FILL__ANGLE = 395;
    public static final short FILL__BACKOPACITY = 388;
    public static final short FILL__BLIPFILENAME = 391;
    public static final short FILL__BLIPFLAGS = 392;
    public static final short FILL__CRMOD = 389;
    public static final short FILL__DZTYPE = 405;
    public static final short FILL__FILLBACKCOLOR = 387;
    public static final short FILL__FILLCOLOR = 385;
    public static final short FILL__FILLED = 443;
    public static final short FILL__FILLOPACITY = 386;
    public static final short FILL__FILLTYPE = 384;
    public static final short FILL__FOCUS = 396;
    public static final short FILL__HEIGHT = 394;
    public static final short FILL__HITTESTFILL = 444;
    public static final short FILL__NOFILLHITTEST = 447;
    public static final short FILL__ORIGINX = 408;
    public static final short FILL__ORIGINY = 409;
    public static final short FILL__PATTERNTEXTURE = 390;
    public static final short FILL__RECTBOTTOM = 404;
    public static final short FILL__RECTLEFT = 401;
    public static final short FILL__RECTRIGHT = 403;
    public static final short FILL__RECTTOP = 402;
    public static final short FILL__SHADECOLORS = 407;
    public static final short FILL__SHADEPRESET = 406;
    public static final short FILL__SHADETYPE = 412;
    public static final short FILL__SHAPE = 445;
    public static final short FILL__SHAPEORIGINX = 410;
    public static final short FILL__SHAPEORIGINY = 411;
    public static final short FILL__TOBOTTOM = 400;
    public static final short FILL__TOLEFT = 397;
    public static final short FILL__TORIGHT = 399;
    public static final short FILL__TOTOP = 398;
    public static final short FILL__USERECT = 446;
    public static final short FILL__WIDTH = 393;
    public static final short GEOMETRY__3DOK = 379;
    public static final short GEOMETRY__ADJUST10VALUE = 336;
    public static final short GEOMETRY__ADJUST2VALUE = 328;
    public static final short GEOMETRY__ADJUST3VALUE = 329;
    public static final short GEOMETRY__ADJUST4VALUE = 330;
    public static final short GEOMETRY__ADJUST5VALUE = 331;
    public static final short GEOMETRY__ADJUST6VALUE = 332;
    public static final short GEOMETRY__ADJUST7VALUE = 333;
    public static final short GEOMETRY__ADJUST8VALUE = 334;
    public static final short GEOMETRY__ADJUST9VALUE = 335;
    public static final short GEOMETRY__ADJUSTVALUE = 327;
    public static final short GEOMETRY__BOTTOM = 323;
    public static final short GEOMETRY__FILLOK = 383;
    public static final short GEOMETRY__FILLSHADESHAPEOK = 382;
    public static final short GEOMETRY__GEOTEXTOK = 381;
    public static final short GEOMETRY__LEFT = 320;
    public static final short GEOMETRY__LINEOK = 380;
    public static final short GEOMETRY__RIGHT = 322;
    public static final short GEOMETRY__SEGMENTINFO = 326;
    public static final short GEOMETRY__SHADOWok = 378;
    public static final short GEOMETRY__SHAPEPATH = 324;
    public static final short GEOMETRY__TOP = 321;
    public static final short GEOMETRY__VERTICES = 325;
    public static final short GEOTEXT__ALIGNMENTONCURVE = 194;
    public static final short GEOTEXT__BOLDFONT = 250;
    public static final short GEOTEXT__CHARBOUNDINGBOX = 246;
    public static final short GEOTEXT__DEFAULTPOINTSIZE = 195;
    public static final short GEOTEXT__FONTFAMILYNAME = 197;
    public static final short GEOTEXT__HASTEXTEFFECT = 241;
    public static final short GEOTEXT__ITALICFONT = 251;
    public static final short GEOTEXT__KERNCHARACTERS = 243;
    public static final short GEOTEXT__NOMEASUREALONGPATH = 249;
    public static final short GEOTEXT__REVERSEROWORDER = 240;
    public static final short GEOTEXT__ROTATECHARACTERS = 242;
    public static final short GEOTEXT__RTFTEXT = 193;
    public static final short GEOTEXT__SCALETEXTONPATH = 247;
    public static final short GEOTEXT__SHADOWFONT = 253;
    public static final short GEOTEXT__SMALLCAPSFONT = 254;
    public static final short GEOTEXT__STRETCHCHARHEIGHT = 248;
    public static final short GEOTEXT__STRETCHTOFITSHAPE = 245;
    public static final short GEOTEXT__STRIKETHROUGHFONT = 255;
    public static final short GEOTEXT__TEXTSPACING = 196;
    public static final short GEOTEXT__TIGHTORTRACK = 244;
    public static final short GEOTEXT__UNDERLINEFONT = 252;
    public static final short GEOTEXT__UNICODE = 192;
    public static final short GROUPSHAPE__1DADJUSTMENT = 957;
    public static final short GROUPSHAPE__BEHINDDOCUMENT = 954;
    public static final short GROUPSHAPE__DESCRIPTION = 897;
    public static final short GROUPSHAPE__EDITEDWRAP = 953;
    public static final short GROUPSHAPE__HIDDEN = 958;
    public static final short GROUPSHAPE__HYPERLINK = 898;
    public static final short GROUPSHAPE__ISBUTTON = 956;
    public static final short GROUPSHAPE__ONDBLCLICKNOTIFY = 955;
    public static final short GROUPSHAPE__PRINT = 959;
    public static final short GROUPSHAPE__REGROUPID = 904;
    public static final short GROUPSHAPE__SHAPENAME = 896;
    public static final short GROUPSHAPE__WRAPDISTBOTTOM = 903;
    public static final short GROUPSHAPE__WRAPDISTLEFT = 900;
    public static final short GROUPSHAPE__WRAPDISTRIGHT = 902;
    public static final short GROUPSHAPE__WRAPDISTTOP = 901;
    public static final short GROUPSHAPE__WRAPPOLYGONVERTICES = 899;
    public static final short LINESTYLE__ANYLINE = 508;
    public static final short LINESTYLE__ARROWHEADSOK = 507;
    public static final short LINESTYLE__BACKCOLOR = 450;
    public static final short LINESTYLE__COLOR = 448;
    public static final short LINESTYLE__CRMOD = 451;
    public static final short LINESTYLE__FILLBLIP = 453;
    public static final short LINESTYLE__FILLBLIPFLAGS = 455;
    public static final short LINESTYLE__FILLBLIPNAME = 454;
    public static final short LINESTYLE__FILLDZTYPE = 458;
    public static final short LINESTYLE__FILLHEIGHT = 457;
    public static final short LINESTYLE__FILLWIDTH = 456;
    public static final short LINESTYLE__HITLINETEST = 509;
    public static final short LINESTYLE__LINEDASHING = 462;
    public static final short LINESTYLE__LINEDASHSTYLE = 463;
    public static final short LINESTYLE__LINEENDARROWHEAD = 465;
    public static final short LINESTYLE__LINEENDARROWLENGTH = 469;
    public static final short LINESTYLE__LINEENDARROWWIDTH = 468;
    public static final short LINESTYLE__LINEENDCAPSTYLE = 471;
    public static final short LINESTYLE__LINEESTARTARROWLENGTH = 467;
    public static final short LINESTYLE__LINEFILLSHAPE = 510;
    public static final short LINESTYLE__LINEJOINSTYLE = 470;
    public static final short LINESTYLE__LINEMITERLIMIT = 460;
    public static final short LINESTYLE__LINESTARTARROWHEAD = 464;
    public static final short LINESTYLE__LINESTARTARROWWIDTH = 466;
    public static final short LINESTYLE__LINESTYLE = 461;
    public static final short LINESTYLE__LINETYPE = 452;
    public static final short LINESTYLE__LINEWIDTH = 459;
    public static final short LINESTYLE__NOLINEDRAWDASH = 511;
    public static final short LINESTYLE__OPACITY = 449;
    public static final short PERSPECTIVE__OFFSETX = 577;
    public static final short PERSPECTIVE__OFFSETY = 578;
    public static final short PERSPECTIVE__ORIGINX = 586;
    public static final short PERSPECTIVE__ORIGINY = 587;
    public static final short PERSPECTIVE__PERSPECTIVEON = 639;
    public static final short PERSPECTIVE__PERSPECTIVEX = 583;
    public static final short PERSPECTIVE__PERSPECTIVEY = 584;
    public static final short PERSPECTIVE__SCALEXTOX = 579;
    public static final short PERSPECTIVE__SCALEXTOY = 581;
    public static final short PERSPECTIVE__SCALEYTOX = 580;
    public static final short PERSPECTIVE__SCALEYTOY = 582;
    public static final short PERSPECTIVE__TYPE = 576;
    public static final short PERSPECTIVE__WEIGHT = 585;
    public static final short PROTECTION__LOCKADJUSTHANDLES = 126;
    public static final short PROTECTION__LOCKAGAINSTGROUPING = 127;
    public static final short PROTECTION__LOCKAGAINSTSELECT = 122;
    public static final short PROTECTION__LOCKASPECTRATIO = 120;
    public static final short PROTECTION__LOCKCROPPING = 123;
    public static final short PROTECTION__LOCKPOSITION = 121;
    public static final short PROTECTION__LOCKROTATION = 119;
    public static final short PROTECTION__LOCKTEXT = 125;
    public static final short PROTECTION__LOCKVERTICES = 124;
    public static final short SHADOWSTYLE__COLOR = 513;
    public static final short SHADOWSTYLE__CRMOD = 515;
    public static final short SHADOWSTYLE__HIGHLIGHT = 514;
    public static final short SHADOWSTYLE__OFFSETX = 517;
    public static final short SHADOWSTYLE__OFFSETY = 518;
    public static final short SHADOWSTYLE__OPACITY = 516;
    public static final short SHADOWSTYLE__ORIGINX = 528;
    public static final short SHADOWSTYLE__ORIGINY = 529;
    public static final short SHADOWSTYLE__PERSPECTIVEX = 525;
    public static final short SHADOWSTYLE__PERSPECTIVEY = 526;
    public static final short SHADOWSTYLE__SCALEXTOX = 521;
    public static final short SHADOWSTYLE__SCALEXTOY = 523;
    public static final short SHADOWSTYLE__SCALEYTOX = 522;
    public static final short SHADOWSTYLE__SCALEYTOY = 524;
    public static final short SHADOWSTYLE__SECONDOFFSETX = 519;
    public static final short SHADOWSTYLE__SECONDOFFSETY = 520;
    public static final short SHADOWSTYLE__SHADOW = 574;
    public static final short SHADOWSTYLE__SHADOWOBSURED = 575;
    public static final short SHADOWSTYLE__TYPE = 512;
    public static final short SHADOWSTYLE__WEIGHT = 527;
    public static final short SHAPE__BACKGROUNDSHAPE = 831;
    public static final short SHAPE__BLACKANDWHITESETTINGS = 772;
    public static final short SHAPE__CONNECTORSTYLE = 771;
    public static final short SHAPE__DELETEATTACHEDOBJECT = 830;
    public static final short SHAPE__LOCKSHAPETYPE = 828;
    public static final short SHAPE__MASTER = 769;
    public static final short SHAPE__OLEICON = 826;
    public static final short SHAPE__PREFERRELATIVERESIZE = 827;
    public static final short SHAPE__WMODEBW = 774;
    public static final short SHAPE__WMODEPUREBW = 773;
    public static final short TEXT__ANCHORTEXT = 135;
    public static final short TEXT__BIDIR = 139;
    public static final short TEXT__FONTROTATION = 137;
    public static final short TEXT__IDOFNEXTSHAPE = 138;
    public static final short TEXT__ROTATETEXTWITHSHAPE = 189;
    public static final short TEXT__SCALETEXT = 134;
    public static final short TEXT__SINGLECLICKSELECTS = 187;
    public static final short TEXT__SIZESHAPETOFITTEXT = 190;
    public static final short TEXT__SIZE_TEXT_TO_FIT_SHAPE = 191;
    public static final short TEXT__TEXTBOTTOM = 132;
    public static final short TEXT__TEXTFLOW = 136;
    public static final short TEXT__TEXTID = 128;
    public static final short TEXT__TEXTLEFT = 129;
    public static final short TEXT__TEXTRIGHT = 131;
    public static final short TEXT__TEXTTOP = 130;
    public static final short TEXT__USEHOSTMARGINS = 188;
    public static final short TEXT__WRAPTEXT = 133;
    public static final short THREEDSTYLE__AMBIENTINTENSITY = 722;
    public static final short THREEDSTYLE__CONSTRAINROTATION = 763;
    public static final short THREEDSTYLE__FILLHARSH = 767;
    public static final short THREEDSTYLE__FILLINTENSITY = 730;
    public static final short THREEDSTYLE__FILLX = 727;
    public static final short THREEDSTYLE__FILLY = 728;
    public static final short THREEDSTYLE__FILLZ = 729;
    public static final short THREEDSTYLE__KEYHARSH = 766;
    public static final short THREEDSTYLE__KEYINTENSITY = 726;
    public static final short THREEDSTYLE__KEYX = 723;
    public static final short THREEDSTYLE__KEYY = 724;
    public static final short THREEDSTYLE__KEYZ = 725;
    public static final short THREEDSTYLE__ORIGINX = 718;
    public static final short THREEDSTYLE__ORIGINY = 719;
    public static final short THREEDSTYLE__PARALLEL = 765;
    public static final short THREEDSTYLE__RENDERMODE = 713;
    public static final short THREEDSTYLE__ROTATIONANGLE = 709;
    public static final short THREEDSTYLE__ROTATIONAXISX = 706;
    public static final short THREEDSTYLE__ROTATIONAXISY = 707;
    public static final short THREEDSTYLE__ROTATIONAXISZ = 708;
    public static final short THREEDSTYLE__ROTATIONCENTERAUTO = 764;
    public static final short THREEDSTYLE__ROTATIONCENTERX = 710;
    public static final short THREEDSTYLE__ROTATIONCENTERY = 711;
    public static final short THREEDSTYLE__ROTATIONCENTERZ = 712;
    public static final short THREEDSTYLE__SKEWAMOUNT = 721;
    public static final short THREEDSTYLE__SKEWANGLE = 720;
    public static final short THREEDSTYLE__TOLERANCE = 714;
    public static final short THREEDSTYLE__XROTATIONANGLE = 705;
    public static final short THREEDSTYLE__XVIEWPOINT = 715;
    public static final short THREEDSTYLE__YROTATIONANGLE = 704;
    public static final short THREEDSTYLE__YVIEWPOINT = 716;
    public static final short THREEDSTYLE__ZVIEWPOINT = 717;
    public static final short THREED__3DEFFECT = 700;
    public static final short THREED__CRMOD = 648;
    public static final short THREED__DIFFUSEAMOUNT = 661;
    public static final short THREED__EDGETHICKNESS = 663;
    public static final short THREED__EXTRUDEBACKWARD = 665;
    public static final short THREED__EXTRUDEFORWARD = 664;
    public static final short THREED__EXTRUDEPLANE = 666;
    public static final short THREED__EXTRUSIONCOLOR = 667;
    public static final short THREED__LIGHTFACE = 703;
    public static final short THREED__METALLIC = 701;
    public static final short THREED__SHININESS = 662;
    public static final short THREED__SPECULARAMOUNT = 640;
    public static final short THREED__USEEXTRUSIONCOLOR = 702;
    public static final short TRANSFORM__ROTATION = 4;
    private static Map properties;

    private static void initProps() {
        if (properties == null) {
            properties = new HashMap();
            addProp(4, data("transform.rotation"));
            addProp(119, data("protection.lockrotation"));
            addProp(120, data("protection.lockaspectratio"));
            addProp(121, data("protection.lockposition"));
            addProp(122, data("protection.lockagainstselect"));
            addProp(123, data("protection.lockcropping"));
            addProp(124, data("protection.lockvertices"));
            addProp(125, data("protection.locktext"));
            addProp(126, data("protection.lockadjusthandles"));
            addProp(127, data("protection.lockagainstgrouping", (byte) 1));
            addProp(128, data("text.textid"));
            addProp(129, data("text.textleft"));
            addProp(130, data("text.texttop"));
            addProp(131, data("text.textright"));
            addProp(132, data("text.textbottom"));
            addProp(133, data("text.wraptext"));
            addProp(134, data("text.scaletext"));
            addProp(135, data("text.anchortext"));
            addProp(136, data("text.textflow"));
            addProp(137, data("text.fontrotation"));
            addProp(138, data("text.idofnextshape"));
            addProp(139, data("text.bidir"));
            addProp(187, data("text.singleclickselects"));
            addProp(188, data("text.usehostmargins"));
            addProp(189, data("text.rotatetextwithshape"));
            addProp(190, data("text.sizeshapetofittext"));
            addProp(191, data("text.sizetexttofitshape", (byte) 1));
            addProp(192, data("geotext.unicode"));
            addProp(193, data("geotext.rtftext"));
            addProp(194, data("geotext.alignmentoncurve"));
            addProp(195, data("geotext.defaultpointsize"));
            addProp(196, data("geotext.textspacing"));
            addProp(197, data("geotext.fontfamilyname"));
            addProp(240, data("geotext.reverseroworder"));
            addProp(TelnetCommand.NOP, data("geotext.hastexteffect"));
            addProp(242, data("geotext.rotatecharacters"));
            addProp(TelnetCommand.BREAK, data("geotext.kerncharacters"));
            addProp(TelnetCommand.IP, data("geotext.tightortrack"));
            addProp(TelnetCommand.AO, data("geotext.stretchtofitshape"));
            addProp(TelnetCommand.AYT, data("geotext.charboundingbox"));
            addProp(TelnetCommand.EC, data("geotext.scaletextonpath"));
            addProp(TelnetCommand.EL, data("geotext.stretchcharheight"));
            addProp(TelnetCommand.GA, data("geotext.nomeasurealongpath"));
            addProp(250, data("geotext.boldfont"));
            addProp(251, data("geotext.italicfont"));
            addProp(252, data("geotext.underlinefont"));
            addProp(TelnetCommand.DO, data("geotext.shadowfont"));
            addProp(254, data("geotext.smallcapsfont"));
            addProp(255, data("geotext.strikethroughfont"));
            addProp(256, data("blip.cropfromtop"));
            addProp(257, data("blip.cropfrombottom"));
            addProp(258, data("blip.cropfromleft"));
            addProp(259, data("blip.cropfromright"));
            addProp(260, data("blip.bliptodisplay"));
            addProp(261, data("blip.blipfilename"));
            addProp(262, data("blip.blipflags"));
            addProp(263, data("blip.transparentcolor"));
            addProp(264, data("blip.contrastsetting"));
            addProp(MediaArtistNativeHelper.VideoEffect.ZOOM_OUT, data("blip.brightnesssetting"));
            addProp(MediaArtistNativeHelper.VideoEffect.FIFTIES, data("blip.gamma"));
            addProp(MediaArtistNativeHelper.VideoEffect.COLORRGB16, data("blip.pictureid"));
            addProp(268, data("blip.doublemod"));
            addProp(269, data("blip.picturefillmod"));
            addProp(270, data("blip.pictureline"));
            addProp(271, data("blip.printblip"));
            addProp(BluetoothClass.Device.COMPUTER_HANDHELD_PC_PDA, data("blip.printblipfilename"));
            addProp(273, data("blip.printflags"));
            addProp(316, data("blip.nohittestpicture"));
            addProp(317, data("blip.picturegray"));
            addProp(318, data("blip.picturebilevel"));
            addProp(319, data("blip.pictureactive"));
            addProp(320, data("geometry.left"));
            addProp(321, data("geometry.top"));
            addProp(322, data("geometry.right"));
            addProp(323, data("geometry.bottom"));
            addProp(324, data("geometry.shapepath", (byte) 3));
            addProp(325, data("geometry.vertices", (byte) 5));
            addProp(326, data("geometry.segmentinfo", (byte) 5));
            addProp(327, data("geometry.adjustvalue"));
            addProp(328, data("geometry.adjust2value"));
            addProp(329, data("geometry.adjust3value"));
            addProp(330, data("geometry.adjust4value"));
            addProp(FTPReply.NEED_PASSWORD, data("geometry.adjust5value"));
            addProp(FTPReply.NEED_ACCOUNT, data("geometry.adjust6value"));
            addProp(AMapEngineUtils.ARROW_LINE_SHADOW_TEXTURE_ID, data("geometry.adjust7value"));
            addProp(FTPReply.SECURITY_MECHANISM_IS_OK, data("geometry.adjust8value"));
            addProp(335, data("geometry.adjust9value"));
            addProp(336, data("geometry.adjust10value"));
            addProp(378, data("geometry.shadowOK"));
            addProp(379, data("geometry.3dok"));
            addProp(380, data("geometry.lineok"));
            addProp(NNTPReply.MORE_AUTH_INFO_REQUIRED, data("geometry.geotextok"));
            addProp(382, data("geometry.fillshadeshapeok"));
            addProp(383, data("geometry.fillok", (byte) 1));
            addProp(384, data("fill.filltype"));
            addProp(385, data("fill.fillcolor", (byte) 2));
            addProp(386, data("fill.fillopacity"));
            addProp(387, data("fill.fillbackcolor", (byte) 2));
            addProp(388, data("fill.backopacity"));
            addProp(389, data("fill.crmod"));
            addProp(390, data("fill.patterntexture"));
            addProp(391, data("fill.blipfilename"));
            addProp(392, data("fill.blipflags"));
            addProp(393, data("fill.width"));
            addProp(394, data("fill.height"));
            addProp(395, data("fill.angle"));
            addProp(396, data("fill.focus"));
            addProp(397, data("fill.toleft"));
            addProp(398, data("fill.totop"));
            addProp(399, data("fill.toright"));
            addProp(400, data("fill.tobottom"));
            addProp(401, data("fill.rectleft"));
            addProp(402, data("fill.recttop"));
            addProp(403, data("fill.rectright"));
            addProp(404, data("fill.rectbottom"));
            addProp(UrlQuerySanitizer.IllegalCharacterValueSanitizer.URL_AND_SPACE_LEGAL, data("fill.dztype"));
            addProp(Downloads.Impl.STATUS_NOT_ACCEPTABLE, data("fill.shadepreset"));
            addProp(407, data("fill.shadecolors", (byte) 5));
            addProp(408, data("fill.originx"));
            addProp(409, data("fill.originy"));
            addProp(410, data("fill.shapeoriginx"));
            addProp(411, data("fill.shapeoriginy"));
            addProp(412, data("fill.shadetype"));
            addProp(443, data("fill.filled"));
            addProp(444, data("fill.hittestfill"));
            addProp(445, data("fill.shape"));
            addProp(446, data("fill.userect"));
            addProp(447, data("fill.nofillhittest", (byte) 1));
            addProp(FileUtils.S_IRWXU, data("linestyle.color", (byte) 2));
            addProp(449, data("linestyle.opacity"));
            addProp(450, data("linestyle.backcolor", (byte) 2));
            addProp(451, data("linestyle.crmod"));
            addProp(452, data("linestyle.linetype"));
            addProp(453, data("linestyle.fillblip"));
            addProp(454, data("linestyle.fillblipname"));
            addProp(455, data("linestyle.fillblipflags"));
            addProp(456, data("linestyle.fillwidth"));
            addProp(457, data("linestyle.fillheight"));
            addProp(458, data("linestyle.filldztype"));
            addProp(459, data("linestyle.linewidth"));
            addProp(460, data("linestyle.linemiterlimit"));
            addProp(461, data("linestyle.linestyle"));
            addProp(462, data("linestyle.linedashing"));
            addProp(463, data("linestyle.linedashstyle", (byte) 5));
            addProp(464, data("linestyle.linestartarrowhead"));
            addProp(465, data("linestyle.lineendarrowhead"));
            addProp(466, data("linestyle.linestartarrowwidth"));
            addProp(467, data("linestyle.lineestartarrowlength"));
            addProp(468, data("linestyle.lineendarrowwidth"));
            addProp(469, data("linestyle.lineendarrowlength"));
            addProp(470, data("linestyle.linejoinstyle"));
            addProp(471, data("linestyle.lineendcapstyle"));
            addProp(507, data("linestyle.arrowheadsok"));
            addProp(508, data("linestyle.anyline"));
            addProp(509, data("linestyle.hitlinetest"));
            addProp(510, data("linestyle.linefillshape"));
            addProp(511, data("linestyle.nolinedrawdash", (byte) 1));
            addProp(512, data("shadowstyle.type"));
            addProp(513, data("shadowstyle.color", (byte) 2));
            addProp(514, data("shadowstyle.highlight"));
            addProp(515, data("shadowstyle.crmod"));
            addProp(516, data("shadowstyle.opacity"));
            addProp(517, data("shadowstyle.offsetx"));
            addProp(518, data("shadowstyle.offsety"));
            addProp(519, data("shadowstyle.secondoffsetx"));
            addProp(BluetoothClass.Device.PHONE_CORDLESS, data("shadowstyle.secondoffsety"));
            addProp(521, data("shadowstyle.scalextox"));
            addProp(522, data("shadowstyle.scaleytox"));
            addProp(523, data("shadowstyle.scalextoy"));
            addProp(BluetoothClass.Device.PHONE_SMART, data("shadowstyle.scaleytoy"));
            addProp(525, data("shadowstyle.perspectivex"));
            addProp(526, data("shadowstyle.perspectivey"));
            addProp(527, data("shadowstyle.weight"));
            addProp(BluetoothClass.Device.PHONE_MODEM_OR_GATEWAY, data("shadowstyle.originx"));
            addProp(529, data("shadowstyle.originy"));
            addProp(574, data("shadowstyle.shadow"));
            addProp(575, data("shadowstyle.shadowobsured"));
            addProp(576, data("perspective.type"));
            addProp(577, data("perspective.offsetx"));
            addProp(578, data("perspective.offsety"));
            addProp(579, data("perspective.scalextox"));
            addProp(580, data("perspective.scaleytox"));
            addProp(581, data("perspective.scalextoy"));
            addProp(582, data("perspective.scaleytoy"));
            addProp(583, data("perspective.perspectivex"));
            addProp(584, data("perspective.perspectivey"));
            addProp(585, data("perspective.weight"));
            addProp(586, data("perspective.originx"));
            addProp(587, data("perspective.originy"));
            addProp(639, data("perspective.perspectiveon"));
            addProp(640, data("3d.specularamount"));
            addProp(661, data("3d.diffuseamount"));
            addProp(662, data("3d.shininess"));
            addProp(663, data("3d.edgethickness"));
            addProp(664, data("3d.extrudeforward"));
            addProp(665, data("3d.extrudebackward"));
            addProp(666, data("3d.extrudeplane"));
            addProp(667, data("3d.extrusioncolor", (byte) 2));
            addProp(648, data("3d.crmod"));
            addProp(700, data("3d.3deffect"));
            addProp(MediaPlayer.MEDIA_INFO_BUFFERING_START, data("3d.metallic"));
            addProp(MediaPlayer.MEDIA_INFO_BUFFERING_END, data("3d.useextrusioncolor", (byte) 2));
            addProp(703, data("3d.lightface"));
            addProp(704, data("3dstyle.yrotationangle"));
            addProp(705, data("3dstyle.xrotationangle"));
            addProp(706, data("3dstyle.rotationaxisx"));
            addProp(707, data("3dstyle.rotationaxisy"));
            addProp(708, data("3dstyle.rotationaxisz"));
            addProp(709, data("3dstyle.rotationangle"));
            addProp(710, data("3dstyle.rotationcenterx"));
            addProp(711, data("3dstyle.rotationcentery"));
            addProp(712, data("3dstyle.rotationcenterz"));
            addProp(713, data("3dstyle.rendermode"));
            addProp(714, data("3dstyle.tolerance"));
            addProp(715, data("3dstyle.xviewpoint"));
            addProp(716, data("3dstyle.yviewpoint"));
            addProp(717, data("3dstyle.zviewpoint"));
            addProp(718, data("3dstyle.originx"));
            addProp(719, data("3dstyle.originy"));
            addProp(MediaProperties.HEIGHT_720, data("3dstyle.skewangle"));
            addProp(721, data("3dstyle.skewamount"));
            addProp(722, data("3dstyle.ambientintensity"));
            addProp(723, data("3dstyle.keyx"));
            addProp(724, data("3dstyle.keyy"));
            addProp(725, data("3dstyle.keyz"));
            addProp(726, data("3dstyle.keyintensity"));
            addProp(727, data("3dstyle.fillx"));
            addProp(728, data("3dstyle.filly"));
            addProp(729, data("3dstyle.fillz"));
            addProp(730, data("3dstyle.fillintensity"));
            addProp(763, data("3dstyle.constrainrotation"));
            addProp(764, data("3dstyle.rotationcenterauto"));
            addProp(765, data("3dstyle.parallel"));
            addProp(766, data("3dstyle.keyharsh"));
            addProp(767, data("3dstyle.fillharsh"));
            addProp(769, data("shape.master"));
            addProp(771, data("shape.connectorstyle"));
            addProp(772, data("shape.blackandwhitesettings"));
            addProp(773, data("shape.wmodepurebw"));
            addProp(774, data("shape.wmodebw"));
            addProp(826, data("shape.oleicon"));
            addProp(827, data("shape.preferrelativeresize"));
            addProp(828, data("shape.lockshapetype"));
            addProp(830, data("shape.deleteattachedobject"));
            addProp(831, data("shape.backgroundshape"));
            addProp(832, data("callout.callouttype"));
            addProp(833, data("callout.xycalloutgap"));
            addProp(834, data("callout.calloutangle"));
            addProp(835, data("callout.calloutdroptype"));
            addProp(836, data("callout.calloutdropspecified"));
            addProp(837, data("callout.calloutlengthspecified"));
            addProp(889, data("callout.iscallout"));
            addProp(890, data("callout.calloutaccentbar"));
            addProp(891, data("callout.callouttextborder"));
            addProp(892, data("callout.calloutminusx"));
            addProp(893, data("callout.calloutminusy"));
            addProp(894, data("callout.dropauto"));
            addProp(895, data("callout.lengthspecified"));
            addProp(AudioSystem.DEVICE_OUT_ALL_A2DP, data("groupshape.shapename"));
            addProp(897, data("groupshape.description"));
            addProp(898, data("groupshape.hyperlink"));
            addProp(899, data("groupshape.wrappolygonvertices", (byte) 5));
            addProp(900, data("groupshape.wrapdistleft"));
            addProp(MediaPlayer.MEDIA_INFO_UNSUPPORTED_SUBTITLE, data("groupshape.wrapdisttop"));
            addProp(MediaPlayer.MEDIA_INFO_SUBTITLE_TIMED_OUT, data("groupshape.wrapdistright"));
            addProp(903, data("groupshape.wrapdistbottom"));
            addProp(904, data("groupshape.regroupid"));
            addProp(953, data("groupshape.editedwrap"));
            addProp(954, data("groupshape.behinddocument"));
            addProp(955, data("groupshape.ondblclicknotify"));
            addProp(956, data("groupshape.isbutton"));
            addProp(957, data("groupshape.1dadjustment"));
            addProp(958, data("groupshape.hidden"));
            addProp(959, data("groupshape.print", (byte) 1));
        }
    }

    private static void addProp(int i, EscherPropertyMetaData escherPropertyMetaData) {
        properties.put(new Short((short) i), escherPropertyMetaData);
    }

    private static EscherPropertyMetaData data(String str, byte b) {
        return new EscherPropertyMetaData(str, b);
    }

    private static EscherPropertyMetaData data(String str) {
        return new EscherPropertyMetaData(str);
    }

    public static String getPropertyName(short s) {
        initProps();
        EscherPropertyMetaData escherPropertyMetaData = (EscherPropertyMetaData) properties.get(new Short(s));
        return escherPropertyMetaData == null ? "unknown" : escherPropertyMetaData.getDescription();
    }

    public static byte getPropertyType(short s) {
        initProps();
        EscherPropertyMetaData escherPropertyMetaData = (EscherPropertyMetaData) properties.get(new Short(s));
        if (escherPropertyMetaData == null) {
            return (byte) 0;
        }
        return escherPropertyMetaData.getType();
    }
}
