package org.apache.poi.hssf.record.formula;

import android.bluetooth.BluetoothClass;
import android.media.videoeditor.MediaArtistNativeHelper;
import android.media.videoeditor.MediaProperties;
import android.telephony.PhoneNumberUtils;
import de.innosystec.unrar.unpack.decode.Compress;
import java.lang.reflect.Array;
import okhttp3.internal.http.StatusLine;
import org.apache.commons.net.ftp.FTPClientConfig;
import org.apache.commons.net.ftp.FTPReply;
import org.apache.commons.net.nntp.NNTPReply;
import org.apache.commons.net.ntp.NtpV3Packet;
import org.apache.commons.net.smtp.SMTPReply;
import org.apache.commons.net.telnet.TelnetCommand;
import org.apache.poi.hssf.model.Workbook;
import org.apache.poi.util.BinaryTree;

/* JADX INFO: loaded from: classes3.dex */
public abstract class AbstractFunctionPtg extends OperationPtg {
    public static final String ATTR_NAME = "specialflag";
    public static final short INDEX_EXTERNAL = 255;
    protected byte field_1_num_args;
    protected short field_2_fnc_index;
    protected byte[] paramClass;
    protected byte returnClass;
    private static BinaryTree map = produceHash();
    protected static Object[][] functionData = produceFunctionData();

    @Override // org.apache.poi.hssf.record.formula.Ptg
    public abstract int getSize();

    @Override // org.apache.poi.hssf.record.formula.OperationPtg
    public int getType() {
        return -1;
    }

    @Override // org.apache.poi.hssf.record.formula.Ptg
    public abstract void writeBytes(byte[] bArr, int i);

    @Override // org.apache.poi.hssf.record.formula.Ptg
    public String toString() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("<FunctionPtg>").append("\n").append("   field_1_num_args=").append((int) this.field_1_num_args).append("\n").append("      name         =").append(lookupName(this.field_2_fnc_index)).append("\n").append("   field_2_fnc_index=").append((int) this.field_2_fnc_index).append("\n").append("</FunctionPtg>");
        return stringBuffer.toString();
    }

    public short getFunctionIndex() {
        return this.field_2_fnc_index;
    }

    public String getName() {
        return lookupName(this.field_2_fnc_index);
    }

    @Override // org.apache.poi.hssf.record.formula.Ptg
    public String toFormulaString(Workbook workbook) {
        return getName();
    }

    @Override // org.apache.poi.hssf.record.formula.OperationPtg
    public String toFormulaString(String[] strArr) {
        StringBuffer stringBuffer = new StringBuffer();
        if (this.field_2_fnc_index != 1) {
            stringBuffer.append(getName());
            stringBuffer.append('(');
        }
        if (strArr.length > 0) {
            for (String str : strArr) {
                stringBuffer.append(str);
                stringBuffer.append(PhoneNumberUtils.PAUSE);
            }
            stringBuffer.deleteCharAt(stringBuffer.length() - 1);
        }
        if (this.field_2_fnc_index != 1) {
            stringBuffer.append(")");
        }
        return stringBuffer.toString();
    }

    protected String lookupName(short s) {
        return (String) map.get(new Integer(s));
    }

    protected short lookupIndex(String str) {
        Integer num = (Integer) map.getKeyForValue(str);
        if (num != null) {
            return num.shortValue();
        }
        return (short) 255;
    }

    private static BinaryTree produceHash() {
        BinaryTree binaryTree = new BinaryTree();
        binaryTree.put(new Integer(0), "COUNT");
        binaryTree.put(new Integer(1), ATTR_NAME);
        binaryTree.put(new Integer(2), "ISNA");
        binaryTree.put(new Integer(3), "ISERROR");
        binaryTree.put(new Integer(4), "SUM");
        binaryTree.put(new Integer(5), "AVERAGE");
        binaryTree.put(new Integer(6), "MIN");
        binaryTree.put(new Integer(7), "MAX");
        binaryTree.put(new Integer(8), "ROW");
        binaryTree.put(new Integer(9), "COLUMN");
        binaryTree.put(new Integer(10), "NA");
        binaryTree.put(new Integer(11), "NPV");
        binaryTree.put(new Integer(12), "STDEV");
        binaryTree.put(new Integer(13), "DOLLAR");
        binaryTree.put(new Integer(14), "FIXED");
        binaryTree.put(new Integer(15), "SIN");
        binaryTree.put(new Integer(16), "COS");
        binaryTree.put(new Integer(17), "TAN");
        binaryTree.put(new Integer(18), "ATAN");
        binaryTree.put(new Integer(19), "PI");
        binaryTree.put(new Integer(20), "SQRT");
        binaryTree.put(new Integer(21), "EXP");
        binaryTree.put(new Integer(22), "LN");
        binaryTree.put(new Integer(23), "LOG10");
        binaryTree.put(new Integer(24), "ABS");
        binaryTree.put(new Integer(25), "INT");
        binaryTree.put(new Integer(26), "SIGN");
        binaryTree.put(new Integer(27), "ROUND");
        binaryTree.put(new Integer(28), "LOOKUP");
        binaryTree.put(new Integer(29), "INDEX");
        binaryTree.put(new Integer(30), "REPT");
        binaryTree.put(new Integer(31), "MID");
        binaryTree.put(new Integer(32), "LEN");
        binaryTree.put(new Integer(33), "VALUE");
        binaryTree.put(new Integer(34), "TRUE");
        binaryTree.put(new Integer(35), "FALSE");
        binaryTree.put(new Integer(36), "AND");
        binaryTree.put(new Integer(37), "OR");
        binaryTree.put(new Integer(38), "NOT");
        binaryTree.put(new Integer(39), "MOD");
        binaryTree.put(new Integer(40), "DCOUNT");
        binaryTree.put(new Integer(41), "DSUM");
        binaryTree.put(new Integer(42), "DAVERAGE");
        binaryTree.put(new Integer(43), "DMIN");
        binaryTree.put(new Integer(44), "DMAX");
        binaryTree.put(new Integer(45), "DSTDEV");
        binaryTree.put(new Integer(46), "VAR");
        binaryTree.put(new Integer(47), "DVAR");
        binaryTree.put(new Integer(48), "TEXT");
        binaryTree.put(new Integer(49), "LINEST");
        binaryTree.put(new Integer(50), "TREND");
        binaryTree.put(new Integer(51), "LOGEST");
        binaryTree.put(new Integer(52), "GROWTH");
        binaryTree.put(new Integer(53), "GOTO");
        binaryTree.put(new Integer(54), "HALT");
        binaryTree.put(new Integer(56), "PV");
        binaryTree.put(new Integer(57), "FV");
        binaryTree.put(new Integer(58), "NPER");
        binaryTree.put(new Integer(59), "PMT");
        binaryTree.put(new Integer(60), "RATE");
        binaryTree.put(new Integer(61), "MIRR");
        binaryTree.put(new Integer(62), "IRR");
        binaryTree.put(new Integer(63), "RAND");
        binaryTree.put(new Integer(64), "MATCH");
        binaryTree.put(new Integer(65), "DATE");
        binaryTree.put(new Integer(66), NtpV3Packet.TYPE_TIME);
        binaryTree.put(new Integer(67), "DAY");
        binaryTree.put(new Integer(68), "MONTH");
        binaryTree.put(new Integer(69), "YEAR");
        binaryTree.put(new Integer(70), "WEEKDAY");
        binaryTree.put(new Integer(71), "HOUR");
        binaryTree.put(new Integer(72), "MINUTE");
        binaryTree.put(new Integer(73), "SECOND");
        binaryTree.put(new Integer(74), "NOW");
        binaryTree.put(new Integer(75), "AREAS");
        binaryTree.put(new Integer(76), "ROWS");
        binaryTree.put(new Integer(77), "COLUMNS");
        binaryTree.put(new Integer(78), "OFFSET");
        binaryTree.put(new Integer(79), "ABSREF");
        binaryTree.put(new Integer(80), "RELREF");
        binaryTree.put(new Integer(81), "ARGUMENT");
        binaryTree.put(new Integer(82), "SEARCH");
        binaryTree.put(new Integer(83), "TRANSPOSE");
        binaryTree.put(new Integer(84), "ERROR");
        binaryTree.put(new Integer(85), "STEP");
        binaryTree.put(new Integer(86), "TYPE");
        binaryTree.put(new Integer(87), "ECHO");
        binaryTree.put(new Integer(88), "SETNAME");
        binaryTree.put(new Integer(89), "CALLER");
        binaryTree.put(new Integer(90), "DEREF");
        binaryTree.put(new Integer(91), FTPClientConfig.SYST_NT);
        binaryTree.put(new Integer(92), "SERIES");
        binaryTree.put(new Integer(93), "DOCUMENTS");
        binaryTree.put(new Integer(94), "ACTIVECELL");
        binaryTree.put(new Integer(95), "SELECTION");
        binaryTree.put(new Integer(96), "RESULT");
        binaryTree.put(new Integer(97), "ATAN2");
        binaryTree.put(new Integer(98), "ASIN");
        binaryTree.put(new Integer(99), "ACOS");
        binaryTree.put(new Integer(100), "CHOOSE");
        binaryTree.put(new Integer(101), "HLOOKUP");
        binaryTree.put(new Integer(102), "VLOOKUP");
        binaryTree.put(new Integer(103), "LINKS");
        binaryTree.put(new Integer(104), "INPUT");
        binaryTree.put(new Integer(105), "ISREF");
        binaryTree.put(new Integer(106), "GETFORMULA");
        binaryTree.put(new Integer(107), "GETNAME");
        binaryTree.put(new Integer(108), "SETVALUE");
        binaryTree.put(new Integer(109), "LOG");
        binaryTree.put(new Integer(110), "EXEC");
        binaryTree.put(new Integer(111), "CHAR");
        binaryTree.put(new Integer(112), "LOWER");
        binaryTree.put(new Integer(113), "UPPER");
        binaryTree.put(new Integer(114), "PROPER");
        binaryTree.put(new Integer(115), "LEFT");
        binaryTree.put(new Integer(116), "RIGHT");
        binaryTree.put(new Integer(117), "EXACT");
        binaryTree.put(new Integer(118), "TRIM");
        binaryTree.put(new Integer(119), "REPLACE");
        binaryTree.put(new Integer(120), "SUBSTITUTE");
        binaryTree.put(new Integer(121), "CODE");
        binaryTree.put(new Integer(122), "NAMES");
        binaryTree.put(new Integer(123), "DIRECTORY");
        binaryTree.put(new Integer(124), "FIND");
        binaryTree.put(new Integer(125), "CELL");
        binaryTree.put(new Integer(126), "ISERR");
        binaryTree.put(new Integer(127), "ISTEXT");
        binaryTree.put(new Integer(128), "ISNUMBER");
        binaryTree.put(new Integer(129), "ISBLANK");
        binaryTree.put(new Integer(130), "T");
        binaryTree.put(new Integer(131), "N");
        binaryTree.put(new Integer(132), "FOPEN");
        binaryTree.put(new Integer(133), "FCLOSE");
        binaryTree.put(new Integer(134), "FSIZE");
        binaryTree.put(new Integer(135), "FREADLN");
        binaryTree.put(new Integer(136), "FREAD");
        binaryTree.put(new Integer(137), "FWRITELN");
        binaryTree.put(new Integer(138), "FWRITE");
        binaryTree.put(new Integer(139), "FPOS");
        binaryTree.put(new Integer(140), "DATEVALUE");
        binaryTree.put(new Integer(141), "TIMEVALUE");
        binaryTree.put(new Integer(142), "SLN");
        binaryTree.put(new Integer(143), "SYD");
        binaryTree.put(new Integer(144), "DDB");
        binaryTree.put(new Integer(145), "GETDEF");
        binaryTree.put(new Integer(146), "REFTEXT");
        binaryTree.put(new Integer(147), "TEXTREF");
        binaryTree.put(new Integer(148), "INDIRECT");
        binaryTree.put(new Integer(149), "REGISTER");
        binaryTree.put(new Integer(150), "CALL");
        binaryTree.put(new Integer(151), "ADDBAR");
        binaryTree.put(new Integer(152), "ADDMENU");
        binaryTree.put(new Integer(153), "ADDCOMMAND");
        binaryTree.put(new Integer(154), "ENABLECOMMAND");
        binaryTree.put(new Integer(155), "CHECKCOMMAND");
        binaryTree.put(new Integer(156), "RENAMECOMMAND");
        binaryTree.put(new Integer(157), "SHOWBAR");
        binaryTree.put(new Integer(158), "DELETEMENU");
        binaryTree.put(new Integer(159), "DELETECOMMAND");
        binaryTree.put(new Integer(160), "GETCHARTITEM");
        binaryTree.put(new Integer(161), "DIALOGBOX");
        binaryTree.put(new Integer(162), "CLEAN");
        binaryTree.put(new Integer(163), "MDETERM");
        binaryTree.put(new Integer(164), "MINVERSE");
        binaryTree.put(new Integer(165), "MMULT");
        binaryTree.put(new Integer(166), "FILES");
        binaryTree.put(new Integer(167), "IPMT");
        binaryTree.put(new Integer(168), "PPMT");
        binaryTree.put(new Integer(169), "COUNTA");
        binaryTree.put(new Integer(170), "CANCELKEY");
        binaryTree.put(new Integer(175), "INITIATE");
        binaryTree.put(new Integer(176), "REQUEST");
        binaryTree.put(new Integer(177), "POKE");
        binaryTree.put(new Integer(178), "EXECUTE");
        binaryTree.put(new Integer(179), "TERMINATE");
        binaryTree.put(new Integer(180), "RESTART");
        binaryTree.put(new Integer(181), "HELP");
        binaryTree.put(new Integer(182), "GETBAR");
        binaryTree.put(new Integer(183), "PRODUCT");
        binaryTree.put(new Integer(184), "FACT");
        binaryTree.put(new Integer(185), "GETCELL");
        binaryTree.put(new Integer(186), "GETWORKSPACE");
        binaryTree.put(new Integer(187), "GETWINDOW");
        binaryTree.put(new Integer(188), "GETDOCUMENT");
        binaryTree.put(new Integer(189), "DPRODUCT");
        binaryTree.put(new Integer(190), "ISNONTEXT");
        binaryTree.put(new Integer(191), "GETNOTE");
        binaryTree.put(new Integer(192), "NOTE");
        binaryTree.put(new Integer(193), "STDEVP");
        binaryTree.put(new Integer(194), "VARP");
        binaryTree.put(new Integer(195), "DSTDEVP");
        binaryTree.put(new Integer(196), "DVARP");
        binaryTree.put(new Integer(197), "TRUNC");
        binaryTree.put(new Integer(198), "ISLOGICAL");
        binaryTree.put(new Integer(199), "DCOUNTA");
        binaryTree.put(new Integer(200), "DELETEBAR");
        binaryTree.put(new Integer(201), "UNREGISTER");
        binaryTree.put(new Integer(204), "USDOLLAR");
        binaryTree.put(new Integer(205), "FINDB");
        binaryTree.put(new Integer(206), "SEARCHB");
        binaryTree.put(new Integer(207), "REPLACEB");
        binaryTree.put(new Integer(208), "LEFTB");
        binaryTree.put(new Integer(209), "RIGHTB");
        binaryTree.put(new Integer(210), "MIDB");
        binaryTree.put(new Integer(211), "LENB");
        binaryTree.put(new Integer(212), "ROUNDUP");
        binaryTree.put(new Integer(213), "ROUNDDOWN");
        binaryTree.put(new Integer(214), "ASC");
        binaryTree.put(new Integer(215), "DBCS");
        binaryTree.put(new Integer(216), "RANK");
        binaryTree.put(new Integer(219), "ADDRESS");
        binaryTree.put(new Integer(220), "DAYS360");
        binaryTree.put(new Integer(221), "TODAY");
        binaryTree.put(new Integer(222), "VDB");
        binaryTree.put(new Integer(FTPReply.ENTERING_PASSIVE_MODE), "MEDIAN");
        binaryTree.put(new Integer(228), "SUMPRODUCT");
        binaryTree.put(new Integer(FTPReply.ENTERING_EPSV_MODE), "SINH");
        binaryTree.put(new Integer(230), "COSH");
        binaryTree.put(new Integer(NNTPReply.NEW_NEWSGROUP_LIST_FOLLOWS), "TANH");
        binaryTree.put(new Integer(232), "ASINH");
        binaryTree.put(new Integer(233), "ACOSH");
        binaryTree.put(new Integer(FTPReply.SECURITY_DATA_EXCHANGE_COMPLETE), "ATANH");
        binaryTree.put(new Integer(235), "DGET");
        binaryTree.put(new Integer(TelnetCommand.EOF), "CREATEOBJECT");
        binaryTree.put(new Integer(TelnetCommand.SUSP), "VOLATILE");
        binaryTree.put(new Integer(TelnetCommand.ABORT), "LASTERROR");
        binaryTree.put(new Integer(239), "CUSTOMUNDO");
        binaryTree.put(new Integer(240), "CUSTOMREPEAT");
        binaryTree.put(new Integer(TelnetCommand.NOP), "FORMULACONVERT");
        binaryTree.put(new Integer(242), "GETLINKINFO");
        binaryTree.put(new Integer(TelnetCommand.BREAK), "TEXTBOX");
        binaryTree.put(new Integer(TelnetCommand.IP), "INFO");
        binaryTree.put(new Integer(TelnetCommand.AO), "GROUP");
        binaryTree.put(new Integer(TelnetCommand.AYT), "GETOBJECT");
        binaryTree.put(new Integer(TelnetCommand.EC), "DB");
        binaryTree.put(new Integer(TelnetCommand.EL), "PAUSE");
        binaryTree.put(new Integer(250), "RESUME");
        binaryTree.put(new Integer(252), "FREQUENCY");
        binaryTree.put(new Integer(TelnetCommand.DO), "ADDTOOLBAR");
        binaryTree.put(new Integer(254), "DELETETOOLBAR");
        binaryTree.put(new Integer(255), "externalflag");
        binaryTree.put(new Integer(256), "RESETTOOLBAR");
        binaryTree.put(new Integer(257), "EVALUATE");
        binaryTree.put(new Integer(258), "GETTOOLBAR");
        binaryTree.put(new Integer(259), "GETTOOL");
        binaryTree.put(new Integer(260), "SPELLINGCHECK");
        binaryTree.put(new Integer(261), "ERRORTYPE");
        binaryTree.put(new Integer(262), "APPTITLE");
        binaryTree.put(new Integer(263), "WINDOWTITLE");
        binaryTree.put(new Integer(264), "SAVETOOLBAR");
        binaryTree.put(new Integer(MediaArtistNativeHelper.VideoEffect.ZOOM_OUT), "ENABLETOOL");
        binaryTree.put(new Integer(MediaArtistNativeHelper.VideoEffect.FIFTIES), "PRESSTOOL");
        binaryTree.put(new Integer(MediaArtistNativeHelper.VideoEffect.COLORRGB16), "REGISTERID");
        binaryTree.put(new Integer(268), "GETWORKBOOK");
        binaryTree.put(new Integer(269), "AVEDEV");
        binaryTree.put(new Integer(270), "BETADIST");
        binaryTree.put(new Integer(271), "GAMMALN");
        binaryTree.put(new Integer(BluetoothClass.Device.COMPUTER_HANDHELD_PC_PDA), "BETAINV");
        binaryTree.put(new Integer(273), "BINOMDIST");
        binaryTree.put(new Integer(274), "CHIDIST");
        binaryTree.put(new Integer(275), "CHIINV");
        binaryTree.put(new Integer(BluetoothClass.Device.COMPUTER_PALM_SIZE_PC_PDA), "COMBIN");
        binaryTree.put(new Integer(277), "CONFIDENCE");
        binaryTree.put(new Integer(278), "CRITBINOM");
        binaryTree.put(new Integer(279), "EVEN");
        binaryTree.put(new Integer(BluetoothClass.Device.COMPUTER_WEARABLE), "EXPONDIST");
        binaryTree.put(new Integer(NNTPReply.AUTHENTICATION_ACCEPTED), "FDIST");
        binaryTree.put(new Integer(282), "FINV");
        binaryTree.put(new Integer(283), "FISHER");
        binaryTree.put(new Integer(284), "FISHERINV");
        binaryTree.put(new Integer(285), "FLOOR");
        binaryTree.put(new Integer(286), "GAMMADIST");
        binaryTree.put(new Integer(287), "GAMMAINV");
        binaryTree.put(new Integer(MediaProperties.HEIGHT_288), "CEILING");
        binaryTree.put(new Integer(289), "HYPGEOMDIST");
        binaryTree.put(new Integer(290), "LOGNORMDIST");
        binaryTree.put(new Integer(291), "LOGINV");
        binaryTree.put(new Integer(292), "NEGBINOMDIST");
        binaryTree.put(new Integer(293), "NORMDIST");
        binaryTree.put(new Integer(294), "NORMSDIST");
        binaryTree.put(new Integer(295), "NORMINV");
        binaryTree.put(new Integer(296), "NORMSINV");
        binaryTree.put(new Integer(297), "STANDARDIZE");
        binaryTree.put(new Integer(Compress.NC20), "ODD");
        binaryTree.put(new Integer(Compress.NC), "PERMUT");
        binaryTree.put(new Integer(300), "POISSON");
        binaryTree.put(new Integer(301), "TDIST");
        binaryTree.put(new Integer(302), "WEIBULL");
        binaryTree.put(new Integer(303), "SUMXMY2");
        binaryTree.put(new Integer(304), "SUMX2MY2");
        binaryTree.put(new Integer(305), "SUMX2PY2");
        binaryTree.put(new Integer(306), "CHITEST");
        binaryTree.put(new Integer(StatusLine.HTTP_TEMP_REDIRECT), "CORREL");
        binaryTree.put(new Integer(StatusLine.HTTP_PERM_REDIRECT), "COVAR");
        binaryTree.put(new Integer(309), "FORECAST");
        binaryTree.put(new Integer(310), "FTEST");
        binaryTree.put(new Integer(311), "INTERCEPT");
        binaryTree.put(new Integer(312), "PEARSON");
        binaryTree.put(new Integer(313), "RSQ");
        binaryTree.put(new Integer(314), "STEYX");
        binaryTree.put(new Integer(315), "SLOPE");
        binaryTree.put(new Integer(316), "TTEST");
        binaryTree.put(new Integer(317), "PROB");
        binaryTree.put(new Integer(318), "DEVSQ");
        binaryTree.put(new Integer(319), "GEOMEAN");
        binaryTree.put(new Integer(320), "HARMEAN");
        binaryTree.put(new Integer(321), "SUMSQ");
        binaryTree.put(new Integer(322), "KURT");
        binaryTree.put(new Integer(323), "SKEW");
        binaryTree.put(new Integer(324), "ZTEST");
        binaryTree.put(new Integer(325), "LARGE");
        binaryTree.put(new Integer(326), "SMALL");
        binaryTree.put(new Integer(327), "QUARTILE");
        binaryTree.put(new Integer(328), "PERCENTILE");
        binaryTree.put(new Integer(329), "PERCENTRANK");
        binaryTree.put(new Integer(330), "MODE");
        binaryTree.put(new Integer(FTPReply.NEED_PASSWORD), "TRIMMEAN");
        binaryTree.put(new Integer(FTPReply.NEED_ACCOUNT), "TINV");
        binaryTree.put(new Integer(FTPReply.SECURITY_MECHANISM_IS_OK), "MOVIECOMMAND");
        binaryTree.put(new Integer(335), "GETMOVIE");
        binaryTree.put(new Integer(336), "CONCATENATE");
        binaryTree.put(new Integer(337), "POWER");
        binaryTree.put(new Integer(338), "PIVOTADDDATA");
        binaryTree.put(new Integer(339), "GETPIVOTTABLE");
        binaryTree.put(new Integer(NNTPReply.SEND_ARTICLE_TO_POST), "GETPIVOTFIELD");
        binaryTree.put(new Integer(341), "GETPIVOTITEM");
        binaryTree.put(new Integer(342), "RADIANS");
        binaryTree.put(new Integer(343), "DEGREES");
        binaryTree.put(new Integer(344), "SUBTOTAL");
        binaryTree.put(new Integer(345), "SUMIF");
        binaryTree.put(new Integer(346), "COUNTIF");
        binaryTree.put(new Integer(347), "COUNTBLANK");
        binaryTree.put(new Integer(348), "SCENARIOGET");
        binaryTree.put(new Integer(349), "OPTIONSLISTSGET");
        binaryTree.put(new Integer(350), "ISPMT");
        binaryTree.put(new Integer(351), "DATEDIF");
        binaryTree.put(new Integer(352), "DATESTRING");
        binaryTree.put(new Integer(353), "NUMBERSTRING");
        binaryTree.put(new Integer(SMTPReply.START_MAIL_INPUT), "ROMAN");
        binaryTree.put(new Integer(355), "OPENDIALOG");
        binaryTree.put(new Integer(356), "SAVEDIALOG");
        binaryTree.put(new Integer(357), "VIEWGET");
        binaryTree.put(new Integer(358), "GETPIVOTDATA");
        binaryTree.put(new Integer(359), "HYPERLINK");
        binaryTree.put(new Integer(360), "PHONETIC");
        binaryTree.put(new Integer(361), "AVERAGEA");
        binaryTree.put(new Integer(362), "MAXA");
        binaryTree.put(new Integer(363), "MINA");
        binaryTree.put(new Integer(364), "STDEVPA");
        binaryTree.put(new Integer(365), "VARPA");
        binaryTree.put(new Integer(366), "STDEVA");
        binaryTree.put(new Integer(367), "VARA");
        return binaryTree;
    }

    private static Object[][] produceFunctionData() {
        Object[][] objArr = (Object[][]) Array.newInstance((Class<?>) Object.class, 368, 3);
        objArr[0][0] = new Byte((byte) 32);
        objArr[0][1] = new byte[]{0};
        objArr[0][2] = new Integer(-1);
        objArr[2][0] = new Byte((byte) 32);
        objArr[2][1] = new byte[]{32};
        objArr[2][2] = new Integer(1);
        objArr[3][0] = new Byte((byte) 32);
        objArr[3][1] = new byte[]{32};
        objArr[3][2] = new Integer(1);
        objArr[4][0] = new Byte((byte) 32);
        objArr[4][1] = new byte[]{0};
        objArr[4][2] = new Integer(-1);
        objArr[5][0] = new Byte((byte) 32);
        objArr[5][1] = new byte[]{0};
        objArr[5][2] = new Integer(-1);
        objArr[6][0] = new Byte((byte) 32);
        objArr[6][1] = new byte[]{0};
        objArr[6][2] = new Integer(-1);
        objArr[7][0] = new Byte((byte) 32);
        objArr[7][1] = new byte[]{0};
        objArr[7][2] = new Integer(-1);
        objArr[8][0] = new Byte((byte) 32);
        objArr[8][1] = new byte[]{0};
        objArr[8][2] = new Integer(-1);
        objArr[9][0] = new Byte((byte) 32);
        objArr[9][1] = new byte[]{0};
        objArr[9][2] = new Integer(-1);
        objArr[10][0] = new Byte((byte) 32);
        objArr[10][1] = new byte[]{32};
        objArr[10][2] = new Integer(0);
        objArr[11][0] = new Byte((byte) 32);
        objArr[11][1] = new byte[]{0};
        objArr[11][2] = new Integer(-1);
        objArr[12][0] = new Byte((byte) 32);
        objArr[12][1] = new byte[]{0};
        objArr[12][2] = new Integer(-1);
        objArr[13][0] = new Byte((byte) 32);
        objArr[13][1] = new byte[]{32};
        objArr[13][2] = new Integer(-1);
        objArr[14][0] = new Byte((byte) 32);
        objArr[14][1] = new byte[]{32};
        objArr[14][2] = new Integer(-1);
        objArr[15][0] = new Byte((byte) 32);
        objArr[15][1] = new byte[]{32};
        objArr[15][2] = new Integer(1);
        objArr[16][0] = new Byte((byte) 32);
        objArr[16][1] = new byte[]{32};
        objArr[16][2] = new Integer(1);
        objArr[17][0] = new Byte((byte) 32);
        objArr[17][1] = new byte[]{32};
        objArr[17][2] = new Integer(1);
        objArr[18][0] = new Byte((byte) 32);
        objArr[18][1] = new byte[]{32};
        objArr[18][2] = new Integer(1);
        objArr[19][0] = new Byte((byte) 32);
        objArr[19][1] = new byte[]{32};
        objArr[19][2] = new Integer(0);
        objArr[20][0] = new Byte((byte) 32);
        objArr[20][1] = new byte[]{32};
        objArr[20][2] = new Integer(1);
        objArr[21][0] = new Byte((byte) 32);
        objArr[21][1] = new byte[]{32};
        objArr[21][2] = new Integer(1);
        objArr[22][0] = new Byte((byte) 32);
        objArr[22][1] = new byte[]{32};
        objArr[22][2] = new Integer(1);
        objArr[23][0] = new Byte((byte) 32);
        objArr[23][1] = new byte[]{32};
        objArr[23][2] = new Integer(1);
        objArr[24][0] = new Byte((byte) 32);
        objArr[24][1] = new byte[]{32};
        objArr[24][2] = new Integer(1);
        objArr[25][0] = new Byte((byte) 32);
        objArr[25][1] = new byte[]{32};
        objArr[25][2] = new Integer(1);
        objArr[26][0] = new Byte((byte) 32);
        objArr[26][1] = new byte[]{32};
        objArr[26][2] = new Integer(1);
        objArr[27][0] = new Byte((byte) 32);
        objArr[27][1] = new byte[]{32};
        objArr[27][2] = new Integer(2);
        objArr[28][0] = new Byte((byte) 32);
        objArr[28][1] = new byte[]{32, 0};
        objArr[28][2] = new Integer(-1);
        objArr[29][0] = new Byte((byte) 32);
        objArr[29][1] = new byte[]{0};
        objArr[29][2] = new Integer(-1);
        objArr[30][0] = new Byte((byte) 32);
        objArr[30][1] = new byte[]{32};
        objArr[30][2] = new Integer(2);
        objArr[31][0] = new Byte((byte) 32);
        objArr[31][1] = new byte[]{32};
        objArr[31][2] = new Integer(3);
        objArr[32][0] = new Byte((byte) 32);
        objArr[32][1] = new byte[]{32};
        objArr[32][2] = new Integer(1);
        objArr[33][0] = new Byte((byte) 32);
        objArr[33][1] = new byte[]{32};
        objArr[33][2] = new Integer(1);
        objArr[34][0] = new Byte((byte) 32);
        objArr[34][1] = new byte[]{32};
        objArr[34][2] = new Integer(1);
        objArr[35][0] = new Byte((byte) 32);
        objArr[35][1] = new byte[]{32};
        objArr[35][2] = new Integer(1);
        objArr[36][0] = new Byte((byte) 32);
        objArr[36][1] = new byte[]{0};
        objArr[36][2] = new Integer(-1);
        objArr[37][0] = new Byte((byte) 32);
        objArr[37][1] = new byte[]{0};
        objArr[37][2] = new Integer(-1);
        objArr[38][0] = new Byte((byte) 32);
        objArr[38][1] = new byte[]{32};
        objArr[38][2] = new Integer(1);
        objArr[39][0] = new Byte((byte) 32);
        objArr[39][1] = new byte[]{32};
        objArr[39][2] = new Integer(2);
        objArr[40][0] = new Byte((byte) 32);
        objArr[40][1] = new byte[]{0};
        objArr[40][2] = new Integer(3);
        objArr[41][0] = new Byte((byte) 32);
        objArr[41][1] = new byte[]{0};
        objArr[41][2] = new Integer(3);
        objArr[42][0] = new Byte((byte) 32);
        objArr[42][1] = new byte[]{0};
        objArr[42][2] = new Integer(3);
        objArr[43][0] = new Byte((byte) 32);
        objArr[43][1] = new byte[]{0};
        objArr[43][2] = new Integer(3);
        objArr[44][0] = new Byte((byte) 32);
        objArr[44][1] = new byte[]{0};
        objArr[44][2] = new Integer(3);
        objArr[45][0] = new Byte((byte) 32);
        objArr[45][1] = new byte[]{0};
        objArr[45][2] = new Integer(3);
        objArr[46][0] = new Byte((byte) 32);
        objArr[46][1] = new byte[]{0};
        objArr[46][2] = new Integer(-1);
        objArr[47][0] = new Byte((byte) 32);
        objArr[47][1] = new byte[]{0};
        objArr[47][2] = new Integer(3);
        objArr[48][0] = new Byte((byte) 32);
        objArr[48][1] = new byte[]{32};
        objArr[48][2] = new Integer(2);
        objArr[49][0] = new Byte((byte) 32);
        objArr[49][1] = new byte[]{0};
        objArr[49][2] = new Integer(-1);
        objArr[50][0] = new Byte((byte) 32);
        objArr[50][1] = new byte[]{0};
        objArr[50][2] = new Integer(-1);
        objArr[51][0] = new Byte((byte) 32);
        objArr[51][1] = new byte[]{0};
        objArr[51][2] = new Integer(-1);
        objArr[52][0] = new Byte((byte) 32);
        objArr[52][1] = new byte[]{0};
        objArr[52][2] = new Integer(-1);
        objArr[56][0] = new Byte((byte) 32);
        objArr[56][1] = new byte[]{32};
        objArr[56][2] = new Integer(-1);
        objArr[57][0] = new Byte((byte) 32);
        objArr[57][1] = new byte[]{32};
        objArr[57][2] = new Integer(-1);
        objArr[58][0] = new Byte((byte) 32);
        objArr[58][1] = new byte[]{32};
        objArr[58][2] = new Integer(-1);
        objArr[59][0] = new Byte((byte) 32);
        objArr[59][1] = new byte[]{32};
        objArr[59][2] = new Integer(-1);
        objArr[60][0] = new Byte((byte) 32);
        objArr[60][1] = new byte[]{32};
        objArr[60][2] = new Integer(-1);
        objArr[61][0] = new Byte((byte) 32);
        objArr[61][1] = new byte[]{32};
        objArr[61][2] = new Integer(3);
        objArr[62][0] = new Byte((byte) 32);
        objArr[62][1] = new byte[]{0};
        objArr[62][2] = new Integer(-1);
        objArr[63][0] = new Byte((byte) 32);
        objArr[63][1] = new byte[]{0};
        objArr[63][2] = new Integer(1);
        objArr[64][0] = new Byte((byte) 32);
        objArr[64][1] = new byte[]{32, 0};
        objArr[64][2] = new Integer(-1);
        objArr[65][0] = new Byte((byte) 32);
        objArr[65][1] = new byte[]{32};
        objArr[65][2] = new Integer(3);
        objArr[66][0] = new Byte((byte) 32);
        objArr[66][1] = new byte[]{32};
        objArr[66][2] = new Integer(3);
        objArr[67][0] = new Byte((byte) 32);
        objArr[67][1] = new byte[]{32};
        objArr[67][2] = new Integer(1);
        objArr[68][0] = new Byte((byte) 32);
        objArr[68][1] = new byte[]{32};
        objArr[68][2] = new Integer(1);
        objArr[69][0] = new Byte((byte) 32);
        objArr[69][1] = new byte[]{32};
        objArr[69][2] = new Integer(1);
        objArr[70][0] = new Byte((byte) 32);
        objArr[70][1] = new byte[]{32};
        objArr[70][2] = new Integer(-1);
        objArr[71][0] = new Byte((byte) 32);
        objArr[71][1] = new byte[]{32};
        objArr[71][2] = new Integer(1);
        objArr[72][0] = new Byte((byte) 32);
        objArr[72][1] = new byte[]{32};
        objArr[72][2] = new Integer(1);
        objArr[73][0] = new Byte((byte) 32);
        objArr[73][1] = new byte[]{32};
        objArr[73][2] = new Integer(1);
        objArr[74][0] = new Byte((byte) 32);
        objArr[74][1] = new byte[]{0};
        objArr[74][2] = new Integer(1);
        objArr[75][0] = new Byte((byte) 32);
        objArr[75][1] = new byte[]{0};
        objArr[75][2] = new Integer(1);
        objArr[76][0] = new Byte((byte) 32);
        objArr[76][1] = new byte[]{0};
        objArr[76][2] = new Integer(1);
        objArr[77][0] = new Byte((byte) 32);
        objArr[77][1] = new byte[]{0};
        objArr[77][2] = new Integer(1);
        objArr[78][0] = new Byte((byte) 32);
        objArr[78][1] = new byte[]{32};
        objArr[78][2] = new Integer(-1);
        objArr[82][0] = new Byte((byte) 32);
        objArr[82][1] = new byte[]{32};
        objArr[82][2] = new Integer(-1);
        objArr[83][0] = new Byte((byte) 32);
        objArr[83][1] = new byte[]{32};
        objArr[83][2] = new Integer(1);
        objArr[86][0] = new Byte((byte) 32);
        objArr[86][1] = new byte[]{32};
        objArr[86][2] = new Integer(1);
        objArr[97][0] = new Byte((byte) 32);
        objArr[97][1] = new byte[]{32};
        objArr[97][2] = new Integer(2);
        objArr[98][0] = new Byte((byte) 32);
        objArr[98][1] = new byte[]{32};
        objArr[98][2] = new Integer(1);
        objArr[99][0] = new Byte((byte) 32);
        objArr[99][1] = new byte[]{32};
        objArr[99][2] = new Integer(1);
        objArr[101][0] = new Byte((byte) 32);
        objArr[101][1] = new byte[]{0};
        objArr[101][2] = new Integer(-1);
        objArr[102][0] = new Byte((byte) 32);
        objArr[102][1] = new byte[]{0};
        objArr[102][2] = new Integer(-1);
        objArr[105][0] = new Byte((byte) 32);
        objArr[105][1] = new byte[]{0};
        objArr[105][2] = new Integer(1);
        objArr[109][0] = new Byte((byte) 32);
        objArr[109][1] = new byte[]{32};
        objArr[109][2] = new Integer(-1);
        objArr[111][0] = new Byte((byte) 32);
        objArr[111][1] = new byte[]{32};
        objArr[111][2] = new Integer(1);
        objArr[112][0] = new Byte((byte) 32);
        objArr[112][1] = new byte[]{32};
        objArr[112][2] = new Integer(1);
        objArr[113][0] = new Byte((byte) 32);
        objArr[113][1] = new byte[]{32};
        objArr[113][2] = new Integer(1);
        objArr[114][0] = new Byte((byte) 32);
        objArr[114][1] = new byte[]{32};
        objArr[114][2] = new Integer(1);
        objArr[115][0] = new Byte((byte) 32);
        objArr[115][1] = new byte[]{32};
        objArr[115][2] = new Integer(-1);
        objArr[116][0] = new Byte((byte) 32);
        objArr[116][1] = new byte[]{32};
        objArr[116][2] = new Integer(-1);
        objArr[117][0] = new Byte((byte) 32);
        objArr[117][1] = new byte[]{32};
        objArr[117][2] = new Integer(2);
        objArr[118][0] = new Byte((byte) 32);
        objArr[118][1] = new byte[]{32};
        objArr[118][2] = new Integer(1);
        objArr[119][0] = new Byte((byte) 32);
        objArr[119][1] = new byte[]{32};
        objArr[119][2] = new Integer(4);
        objArr[120][0] = new Byte((byte) 32);
        objArr[120][1] = new byte[]{32};
        objArr[120][2] = new Integer(-1);
        objArr[121][0] = new Byte((byte) 32);
        objArr[121][1] = new byte[]{32};
        objArr[121][2] = new Integer(1);
        objArr[124][0] = new Byte((byte) 32);
        objArr[124][1] = new byte[]{32};
        objArr[124][2] = new Integer(-1);
        objArr[125][0] = new Byte((byte) 32);
        objArr[125][1] = new byte[]{32};
        objArr[125][2] = new Integer(-1);
        objArr[126][0] = new Byte((byte) 32);
        objArr[126][1] = new byte[]{32};
        objArr[126][2] = new Integer(1);
        objArr[127][0] = new Byte((byte) 32);
        objArr[127][1] = new byte[]{32};
        objArr[127][2] = new Integer(1);
        objArr[128][0] = new Byte((byte) 32);
        objArr[128][1] = new byte[]{32};
        objArr[128][2] = new Integer(1);
        objArr[129][0] = new Byte((byte) 32);
        objArr[129][1] = new byte[]{32};
        objArr[129][2] = new Integer(1);
        objArr[130][0] = new Byte((byte) 32);
        objArr[130][1] = new byte[]{0};
        objArr[130][2] = new Integer(1);
        objArr[131][0] = new Byte((byte) 32);
        objArr[131][1] = new byte[]{0};
        objArr[131][2] = new Integer(1);
        objArr[140][0] = new Byte((byte) 32);
        objArr[140][1] = new byte[]{32};
        objArr[140][2] = new Integer(1);
        objArr[141][0] = new Byte((byte) 32);
        objArr[141][1] = new byte[]{32};
        objArr[141][2] = new Integer(1);
        objArr[142][0] = new Byte((byte) 32);
        objArr[142][1] = new byte[]{32};
        objArr[142][2] = new Integer(3);
        objArr[148][0] = new Byte((byte) 32);
        objArr[148][1] = new byte[]{32};
        objArr[148][2] = new Integer(-1);
        objArr[150][0] = new Byte((byte) 32);
        objArr[150][1] = new byte[]{32};
        objArr[150][2] = new Integer(-1);
        objArr[162][0] = new Byte((byte) 32);
        objArr[162][1] = new byte[]{32};
        objArr[162][2] = new Integer(1);
        objArr[163][0] = new Byte((byte) 32);
        objArr[163][1] = new byte[]{64};
        objArr[163][2] = new Integer(1);
        objArr[164][0] = new Byte((byte) 32);
        objArr[164][1] = new byte[]{64};
        objArr[164][2] = new Integer(1);
        objArr[165][0] = new Byte((byte) 32);
        objArr[165][1] = new byte[]{64};
        objArr[165][2] = new Integer(2);
        objArr[166][0] = new Byte((byte) 32);
        objArr[166][1] = new byte[]{32};
        objArr[166][2] = new Integer(-1);
        objArr[167][0] = new Byte((byte) 32);
        objArr[167][1] = new byte[]{32};
        objArr[167][2] = new Integer(-1);
        objArr[168][0] = new Byte((byte) 32);
        objArr[168][1] = new byte[]{0};
        objArr[168][2] = new Integer(-1);
        objArr[183][0] = new Byte((byte) 32);
        objArr[183][1] = new byte[]{0};
        objArr[183][2] = new Integer(-1);
        objArr[184][0] = new Byte((byte) 32);
        objArr[184][1] = new byte[]{32};
        objArr[184][2] = new Integer(1);
        objArr[189][0] = new Byte((byte) 32);
        objArr[189][1] = new byte[]{0};
        objArr[189][2] = new Integer(3);
        objArr[190][0] = new Byte((byte) 32);
        objArr[190][1] = new byte[]{32};
        objArr[190][2] = new Integer(1);
        objArr[193][0] = new Byte((byte) 32);
        objArr[193][1] = new byte[]{0};
        objArr[193][2] = new Integer(-1);
        objArr[194][0] = new Byte((byte) 32);
        objArr[194][1] = new byte[]{0};
        objArr[194][2] = new Integer(-1);
        objArr[195][0] = new Byte((byte) 32);
        objArr[195][1] = new byte[]{0};
        objArr[195][2] = new Integer(3);
        objArr[196][0] = new Byte((byte) 32);
        objArr[196][1] = new byte[]{0};
        objArr[196][2] = new Integer(3);
        objArr[197][0] = new Byte((byte) 32);
        objArr[197][1] = new byte[]{32};
        objArr[197][2] = new Integer(-1);
        objArr[198][0] = new Byte((byte) 32);
        objArr[198][1] = new byte[]{32};
        objArr[198][2] = new Integer(1);
        objArr[199][0] = new Byte((byte) 32);
        objArr[199][1] = new byte[]{0};
        objArr[199][2] = new Integer(3);
        objArr[204][0] = new Byte((byte) 32);
        objArr[204][1] = new byte[]{32};
        objArr[204][2] = new Integer(-1);
        objArr[205][0] = new Byte((byte) 32);
        objArr[205][1] = new byte[]{32};
        objArr[205][2] = new Integer(-1);
        objArr[206][0] = new Byte((byte) 32);
        objArr[206][1] = new byte[]{32};
        objArr[206][2] = new Integer(-1);
        objArr[207][0] = new Byte((byte) 32);
        objArr[207][1] = new byte[]{32};
        objArr[207][2] = new Integer(3);
        objArr[208][0] = new Byte((byte) 32);
        objArr[208][1] = new byte[]{32};
        objArr[208][2] = new Integer(1);
        objArr[209][0] = new Byte((byte) 32);
        objArr[209][1] = new byte[]{32};
        objArr[209][2] = new Integer(2);
        objArr[210][0] = new Byte((byte) 32);
        objArr[210][1] = new byte[]{32};
        objArr[210][2] = new Integer(2);
        objArr[211][0] = new Byte((byte) 32);
        objArr[211][1] = new byte[]{32};
        objArr[211][2] = new Integer(1);
        objArr[212][0] = new Byte((byte) 32);
        objArr[212][1] = new byte[]{32};
        objArr[212][2] = new Integer(1);
        objArr[213][0] = new Byte((byte) 32);
        objArr[213][1] = new byte[]{0};
        objArr[213][2] = new Integer(-1);
        objArr[214][0] = new Byte((byte) 32);
        objArr[214][1] = new byte[]{32};
        objArr[214][2] = new Integer(-1);
        objArr[221][0] = new Byte((byte) 32);
        objArr[221][1] = new byte[]{0};
        objArr[221][2] = new Integer(1);
        objArr[222][0] = new Byte((byte) 32);
        objArr[222][1] = new byte[]{32};
        objArr[222][2] = new Integer(-1);
        objArr[227][0] = new Byte((byte) 32);
        objArr[227][1] = new byte[]{0};
        objArr[227][2] = new Integer(-1);
        objArr[228][0] = new Byte((byte) 32);
        objArr[228][1] = new byte[]{64};
        objArr[228][2] = new Integer(-1);
        objArr[229][0] = new Byte((byte) 32);
        objArr[229][1] = new byte[]{32};
        objArr[229][2] = new Integer(1);
        objArr[230][0] = new Byte((byte) 32);
        objArr[230][1] = new byte[]{32};
        objArr[230][2] = new Integer(1);
        objArr[231][0] = new Byte((byte) 32);
        objArr[231][1] = new byte[]{32};
        objArr[231][2] = new Integer(1);
        objArr[232][0] = new Byte((byte) 32);
        objArr[232][1] = new byte[]{32};
        objArr[232][2] = new Integer(1);
        objArr[233][0] = new Byte((byte) 32);
        objArr[233][1] = new byte[]{32};
        objArr[233][2] = new Integer(1);
        objArr[234][0] = new Byte((byte) 32);
        objArr[234][1] = new byte[]{32};
        objArr[234][2] = new Integer(1);
        objArr[235][0] = new Byte((byte) 32);
        objArr[235][1] = new byte[]{0};
        objArr[235][2] = new Integer(3);
        objArr[244][0] = new Byte((byte) 32);
        objArr[244][1] = new byte[]{32};
        objArr[244][2] = new Integer(2);
        objArr[252][0] = new Byte((byte) 32);
        objArr[252][1] = new byte[]{0};
        objArr[252][2] = new Integer(2);
        objArr[269][0] = new Byte((byte) 32);
        objArr[269][1] = new byte[]{0};
        objArr[269][2] = new Integer(-1);
        objArr[270][0] = new Byte((byte) 32);
        objArr[270][1] = new byte[]{32};
        objArr[270][2] = new Integer(-1);
        objArr[271][0] = new Byte((byte) 32);
        objArr[271][1] = new byte[]{32};
        objArr[271][2] = new Integer(1);
        objArr[272][0] = new Byte((byte) 32);
        objArr[272][1] = new byte[]{32};
        objArr[272][2] = new Integer(-1);
        objArr[273][0] = new Byte((byte) 32);
        objArr[273][1] = new byte[]{32};
        objArr[273][2] = new Integer(4);
        objArr[274][0] = new Byte((byte) 32);
        objArr[274][1] = new byte[]{32};
        objArr[274][2] = new Integer(2);
        objArr[275][0] = new Byte((byte) 32);
        objArr[275][1] = new byte[]{32};
        objArr[275][2] = new Integer(2);
        objArr[276][0] = new Byte((byte) 32);
        objArr[276][1] = new byte[]{32};
        objArr[276][2] = new Integer(2);
        objArr[277][0] = new Byte((byte) 32);
        objArr[277][1] = new byte[]{32};
        objArr[277][2] = new Integer(3);
        objArr[278][0] = new Byte((byte) 32);
        objArr[278][1] = new byte[]{32};
        objArr[278][2] = new Integer(3);
        objArr[279][0] = new Byte((byte) 32);
        objArr[279][1] = new byte[]{32};
        objArr[279][2] = new Integer(1);
        objArr[280][0] = new Byte((byte) 32);
        objArr[280][1] = new byte[]{32};
        objArr[280][2] = new Integer(3);
        objArr[281][0] = new Byte((byte) 32);
        objArr[281][1] = new byte[]{32};
        objArr[281][2] = new Integer(3);
        objArr[282][0] = new Byte((byte) 32);
        objArr[282][1] = new byte[]{32};
        objArr[282][2] = new Integer(3);
        objArr[283][0] = new Byte((byte) 32);
        objArr[283][1] = new byte[]{32};
        objArr[283][2] = new Integer(1);
        objArr[284][0] = new Byte((byte) 32);
        objArr[284][1] = new byte[]{32};
        objArr[284][2] = new Integer(1);
        objArr[285][0] = new Byte((byte) 32);
        objArr[285][1] = new byte[]{32};
        objArr[285][2] = new Integer(2);
        objArr[286][0] = new Byte((byte) 32);
        objArr[286][1] = new byte[]{32};
        objArr[286][2] = new Integer(4);
        objArr[287][0] = new Byte((byte) 32);
        objArr[287][1] = new byte[]{32};
        objArr[287][2] = new Integer(3);
        objArr[288][0] = new Byte((byte) 32);
        objArr[288][1] = new byte[]{32};
        objArr[288][2] = new Integer(2);
        objArr[289][0] = new Byte((byte) 32);
        objArr[289][1] = new byte[]{32};
        objArr[289][2] = new Integer(4);
        objArr[290][0] = new Byte((byte) 32);
        objArr[290][1] = new byte[]{32};
        objArr[290][2] = new Integer(3);
        objArr[291][0] = new Byte((byte) 32);
        objArr[291][1] = new byte[]{32};
        objArr[291][2] = new Integer(3);
        objArr[292][0] = new Byte((byte) 32);
        objArr[292][1] = new byte[]{32};
        objArr[292][2] = new Integer(3);
        objArr[293][0] = new Byte((byte) 32);
        objArr[293][1] = new byte[]{32};
        objArr[293][2] = new Integer(4);
        objArr[294][0] = new Byte((byte) 32);
        objArr[294][1] = new byte[]{32};
        objArr[294][2] = new Integer(1);
        objArr[295][0] = new Byte((byte) 32);
        objArr[295][1] = new byte[]{32};
        objArr[295][2] = new Integer(3);
        objArr[296][0] = new Byte((byte) 32);
        objArr[296][1] = new byte[]{32};
        objArr[296][2] = new Integer(1);
        objArr[297][0] = new Byte((byte) 32);
        objArr[297][1] = new byte[]{32};
        objArr[297][2] = new Integer(3);
        objArr[298][0] = new Byte((byte) 32);
        objArr[298][1] = new byte[]{32};
        objArr[298][2] = new Integer(1);
        objArr[299][0] = new Byte((byte) 32);
        objArr[299][1] = new byte[]{32};
        objArr[299][2] = new Integer(2);
        objArr[300][0] = new Byte((byte) 32);
        objArr[300][1] = new byte[]{32};
        objArr[300][2] = new Integer(3);
        objArr[301][0] = new Byte((byte) 32);
        objArr[301][1] = new byte[]{32};
        objArr[301][2] = new Integer(3);
        objArr[302][0] = new Byte((byte) 32);
        objArr[302][1] = new byte[]{32};
        objArr[302][2] = new Integer(4);
        objArr[303][0] = new Byte((byte) 32);
        objArr[303][1] = new byte[]{64};
        objArr[303][2] = new Integer(2);
        objArr[304][0] = new Byte((byte) 32);
        objArr[304][1] = new byte[]{64};
        objArr[304][2] = new Integer(2);
        objArr[305][0] = new Byte((byte) 32);
        objArr[305][1] = new byte[]{64};
        objArr[305][2] = new Integer(2);
        objArr[306][0] = new Byte((byte) 32);
        objArr[306][1] = new byte[]{64};
        objArr[306][2] = new Integer(2);
        objArr[307][0] = new Byte((byte) 32);
        objArr[307][1] = new byte[]{64};
        objArr[307][2] = new Integer(2);
        objArr[308][0] = new Byte((byte) 32);
        objArr[308][1] = new byte[]{64};
        objArr[308][2] = new Integer(2);
        objArr[309][0] = new Byte((byte) 32);
        objArr[309][1] = new byte[]{64};
        objArr[309][2] = new Integer(3);
        objArr[310][0] = new Byte((byte) 32);
        objArr[310][1] = new byte[]{64};
        objArr[310][2] = new Integer(2);
        objArr[311][0] = new Byte((byte) 32);
        objArr[311][1] = new byte[]{64};
        objArr[311][2] = new Integer(2);
        objArr[312][0] = new Byte((byte) 32);
        objArr[312][1] = new byte[]{64};
        objArr[312][2] = new Integer(2);
        objArr[313][0] = new Byte((byte) 32);
        objArr[313][1] = new byte[]{64};
        objArr[313][2] = new Integer(2);
        objArr[314][0] = new Byte((byte) 32);
        objArr[314][1] = new byte[]{64};
        objArr[314][2] = new Integer(2);
        objArr[315][0] = new Byte((byte) 32);
        objArr[315][1] = new byte[]{64};
        objArr[315][2] = new Integer(2);
        objArr[316][0] = new Byte((byte) 32);
        objArr[316][1] = new byte[]{32};
        objArr[316][2] = new Integer(4);
        objArr[317][0] = new Byte((byte) 32);
        objArr[317][1] = new byte[]{32};
        objArr[317][2] = new Integer(-1);
        objArr[318][0] = new Byte((byte) 32);
        objArr[318][1] = new byte[]{0};
        objArr[318][2] = new Integer(-1);
        objArr[319][0] = new Byte((byte) 32);
        objArr[319][1] = new byte[]{0};
        objArr[319][2] = new Integer(-1);
        objArr[320][0] = new Byte((byte) 32);
        objArr[320][1] = new byte[]{0};
        objArr[320][2] = new Integer(-1);
        objArr[321][0] = new Byte((byte) 32);
        objArr[321][1] = new byte[]{0};
        objArr[321][2] = new Integer(-1);
        objArr[322][0] = new Byte((byte) 32);
        objArr[322][1] = new byte[]{0};
        objArr[322][2] = new Integer(-1);
        objArr[323][0] = new Byte((byte) 32);
        objArr[323][1] = new byte[]{0};
        objArr[323][2] = new Integer(-1);
        objArr[324][0] = new Byte((byte) 32);
        objArr[324][1] = new byte[]{32};
        objArr[324][2] = new Integer(-1);
        objArr[325][0] = new Byte((byte) 32);
        objArr[325][1] = new byte[]{32};
        objArr[325][2] = new Integer(2);
        objArr[326][0] = new Byte((byte) 32);
        objArr[326][1] = new byte[]{32};
        objArr[326][2] = new Integer(2);
        objArr[327][0] = new Byte((byte) 32);
        objArr[327][1] = new byte[]{32};
        objArr[327][2] = new Integer(2);
        objArr[328][0] = new Byte((byte) 32);
        objArr[328][1] = new byte[]{32};
        objArr[328][2] = new Integer(2);
        objArr[329][0] = new Byte((byte) 32);
        objArr[329][1] = new byte[]{32};
        objArr[329][2] = new Integer(-1);
        objArr[330][0] = new Byte((byte) 32);
        objArr[330][1] = new byte[]{64};
        objArr[330][2] = new Integer(-1);
        objArr[331][0] = new Byte((byte) 32);
        objArr[331][1] = new byte[]{32};
        objArr[331][2] = new Integer(2);
        objArr[332][0] = new Byte((byte) 32);
        objArr[332][1] = new byte[]{32};
        objArr[332][2] = new Integer(2);
        objArr[336][0] = new Byte((byte) 32);
        objArr[336][1] = new byte[]{32};
        objArr[336][2] = new Integer(-1);
        objArr[337][0] = new Byte((byte) 32);
        objArr[337][1] = new byte[]{32};
        objArr[337][2] = new Integer(2);
        objArr[342][0] = new Byte((byte) 32);
        objArr[342][1] = new byte[]{32};
        objArr[342][2] = new Integer(1);
        objArr[343][0] = new Byte((byte) 32);
        objArr[343][1] = new byte[]{32};
        objArr[343][2] = new Integer(1);
        objArr[344][0] = new Byte((byte) 32);
        objArr[344][1] = new byte[]{0};
        objArr[344][2] = new Integer(-1);
        objArr[345][0] = new Byte((byte) 32);
        objArr[345][1] = new byte[]{0};
        objArr[345][2] = new Integer(-1);
        objArr[346][0] = new Byte((byte) 32);
        objArr[346][1] = new byte[]{32};
        objArr[346][2] = new Integer(2);
        objArr[347][0] = new Byte((byte) 32);
        objArr[347][1] = new byte[]{0};
        objArr[347][2] = new Integer(1);
        objArr[350][0] = new Byte((byte) 32);
        objArr[350][1] = new byte[]{32};
        objArr[350][2] = new Integer(4);
        objArr[352][0] = new Byte((byte) 32);
        objArr[352][1] = new byte[]{32};
        objArr[352][2] = new Integer(1);
        objArr[354][0] = new Byte((byte) 32);
        objArr[354][1] = new byte[]{32};
        objArr[354][2] = new Integer(-1);
        objArr[358][0] = new Byte((byte) 32);
        objArr[358][1] = new byte[]{32};
        objArr[358][2] = new Integer(2);
        objArr[359][0] = new Byte((byte) 32);
        objArr[359][1] = new byte[]{32};
        objArr[359][2] = new Integer(-1);
        objArr[360][0] = new Byte((byte) 32);
        objArr[360][1] = new byte[]{0};
        objArr[360][2] = new Integer(1);
        objArr[361][0] = new Byte((byte) 32);
        objArr[361][1] = new byte[]{0};
        objArr[361][2] = new Integer(-1);
        objArr[362][0] = new Byte((byte) 32);
        objArr[362][1] = new byte[]{0};
        objArr[362][2] = new Integer(-1);
        objArr[363][0] = new Byte((byte) 32);
        objArr[363][1] = new byte[]{0};
        objArr[363][2] = new Integer(-1);
        objArr[364][0] = new Byte((byte) 32);
        objArr[364][1] = new byte[]{0};
        objArr[364][2] = new Integer(-1);
        objArr[365][0] = new Byte((byte) 32);
        objArr[365][1] = new byte[]{0};
        objArr[365][2] = new Integer(-1);
        objArr[366][0] = new Byte((byte) 32);
        objArr[366][1] = new byte[]{0};
        objArr[366][2] = new Integer(-1);
        objArr[367][0] = new Byte((byte) 32);
        objArr[367][1] = new byte[]{0};
        objArr[367][2] = new Integer(-1);
        return objArr;
    }

    @Override // org.apache.poi.hssf.record.formula.OperationPtg, org.apache.poi.hssf.record.formula.Ptg
    public byte getDefaultOperandClass() {
        return this.returnClass;
    }

    public byte getParameterClass(int i) {
        try {
            return this.paramClass[i];
        } catch (ArrayIndexOutOfBoundsException unused) {
            return this.paramClass[r2.length - 1];
        }
    }
}
